/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-15 11:38:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user.propertyDeveloper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailedRegistrationPropertyDeveloper_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/common/common.jsp", Long.valueOf(1436246875542L));
    _jspx_dependants.put("/WEB-INF/jsp/user/propertyDeveloper/pdheader.jsp", Long.valueOf(1436246877146L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>The No Voids Man</title>\r\n");
      out.write("<!-- ---------------- Style Sheet --------------------------------->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/style.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap-responsive.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/responsive-media-queries.css\" />\r\n");
      out.write("<link media=\"screen\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/ui-progress-bar.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/jsDatePick_ltr.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/fancybox/jquery.fancybox.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/jquery.remodal.css\" />\r\n");
      out.write("<!-- ---------------- JavaScript --------------------------------->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" function getContextPath() {\r\n");
      out.write("\t   return \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t} \r\n");
      out.write("\tvar contextPath = getContextPath();\r\n");
      out.write("\t//alert(contextPath);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-transition.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-dropdown.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-collapse.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/featherlight.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/fancybox/jquery.fancybox.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jsDatePick.jquery.min.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/form2Object.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/json2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/logout-popup.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("(function() {\n");
      out.write("\t  // Union of Chrome, Firefox, IE, Opera, and Safari console methods\n");
      out.write("\t  var methods = [\"assert\", \"assert\", \"cd\", \"clear\", \"count\", \"countReset\",\n");
      out.write("\t    \"debug\", \"dir\", \"dirxml\", \"dirxml\", \"dirxml\", \"error\", \"error\", \"exception\",\n");
      out.write("\t    \"group\", \"group\", \"groupCollapsed\", \"groupCollapsed\", \"groupEnd\", \"info\",\n");
      out.write("\t    \"info\", \"log\", \"log\", \"markTimeline\", \"profile\", \"profileEnd\", \"profileEnd\",\n");
      out.write("\t    \"select\", \"table\", \"table\", \"time\", \"time\", \"timeEnd\", \"timeEnd\", \"timeEnd\",\n");
      out.write("\t    \"timeEnd\", \"timeEnd\", \"timeStamp\", \"timeline\", \"timelineEnd\", \"trace\",\n");
      out.write("\t    \"trace\", \"trace\", \"trace\", \"trace\", \"warn\"];\n");
      out.write("\t  var length = methods.length;\n");
      out.write("\t  var console = (window.console = window.console || {});\n");
      out.write("\t  var method;\n");
      out.write("\t  var noop = function() {};\n");
      out.write("\t  while (length--) {\n");
      out.write("\t    method = methods[length];\n");
      out.write("\t    // define undefined methods as noops to prevent errors\n");
      out.write("\t    if (!console[method])\n");
      out.write("\t      console[method] = noop;\n");
      out.write("\t  }\n");
      out.write("\t})();\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("    var contextPath ;\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tcontextPath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t\t\t$(\"#logoutBtnId\").click(function(){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t\t      type: \"get\",\n");
      out.write("\t\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t\t      success: function(response){\n");
      out.write("\t\t\t\t    \t  \n");
      out.write("\t\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t\t    \t }\n");
      out.write("\t\t\t\t      },\n");
      out.write("\t\t\t\t      error:function(){\n");
      out.write("\t\t\t\t    \t  console.log('Some error is there.');\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t  });\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#continueBtnId\").click(function(){\n");
      out.write("\t\t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/home.htm\";\n");
      out.write("\t\t\t});\n");
      out.write("\t\tconsole.log(contextPath);\n");
      out.write("\t\t});\n");
      out.write("\tfunction getContextPath() {\n");
      out.write("\t\t   return \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t  var homemaxage = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${homemaxage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t  \n");
      out.write("\t var stop = true;\n");
      out.write("  \t var maxage =\"\";\n");
      out.write("  \t var name = \"maxage\" + \"=\";\n");
      out.write("  \t var intval = 1000;\n");
      out.write("  \t \n");
      out.write("  \t setInterval(function (){\n");
      out.write("  \t\t \n");
      out.write("  \t   \t var cdata = document.cookie.split(';');\n");
      out.write("        // console.log(cdata);\n");
      out.write("         \n");
      out.write("  \t   \t  for(var i=0; i<cdata.length; i++){\n");
      out.write("\n");
      out.write("  \t   \t  \tvar c = cdata[i].trim();\n");
      out.write("  \t   \t  \tif (c.indexOf(\"maxage\")==0){\n");
      out.write("  \t   \t  \t\t\tmaxage = c.substring(name.length,c.length);\n");
      out.write("  \t   \t  \t\t\tif(maxage == homemaxage){\n");
      out.write("  \t   \t  \t\t\t\tdocument.cookie ='maxage='+maxage;\n");
      out.write("  \t   \t  \t\t\t\tstop = true;\n");
      out.write("  \t   \t  \t\t\t}\n");
      out.write("  \t   \t  \t    \tbreak;\t\n");
      out.write("  \t   \t \t\t}\n");
      out.write("  \t   \t  }\n");
      out.write("  \t   \t \n");
      out.write("  \t   \t  if(maxage != null && maxage!=\"\"){\n");
      out.write("  \t   \t\t  maxage = parseInt(maxage)-1000;\n");
      out.write("  \t   \t\t  if(parseInt(maxage) <= 0.00){\n");
      out.write("  \t   \t\t\t  document.cookie =name+\";expires=\"+new Date();\n");
      out.write("  \t   \t\t\t$.ajax({\n");
      out.write("    \t\t\t\t  url: contextPath+\"/home/applicationLogout.htm\",\n");
      out.write("    \t\t\t      type: \"GET\",\n");
      out.write("    \t\t\t      dataType : \"json\",\n");
      out.write("    \t\t\t      success: function(response){\n");
      out.write("    \t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("    \t\t\t    \t\twindow.location.href = contextPath+'/j_spring_security_logout';\n");
      out.write("    \t\t\t    \t }\n");
      out.write("    \t\t\t      },\n");
      out.write("    \t\t\t      error:function(){\n");
      out.write("    \t\t\t         console.log('Some error is there.');\n");
      out.write("    \t\t\t      }\n");
      out.write("    \t\t\t  });\n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t  }\n");
      out.write("  \t   \t\t  document.cookie ='maxage='+maxage;\n");
      out.write("  \t     \t\t  if(parseInt(maxage) < (2*60*1000)){\n");
      out.write("  \t     \t\t\t  if(stop){\n");
      out.write("  \t     \t\t\t\t var logoutStr = getLogoutTime();\n");
      out.write("  \t     \t\t\t\tconsole.log(logoutStr);\n");
      out.write("  \t     \t\t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t\t\tlogoutPopUp('bodyId', 'logoutWindowId');\n");
      out.write("  \t     \t\t\t\tstop =false;\n");
      out.write("  \t     \t\t\t\t\n");
      out.write("  \t     \t\t\t  }\n");
      out.write("  \t     \t\t\t var logoutStr = getLogoutTime();\n");
      out.write("\t     \t\t\t\tconsole.log(\"appending : \" + logoutStr);\n");
      out.write("\t     \t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t  }\n");
      out.write("  \t   \t  }\n");
      out.write("  \t    }, intval);\n");
      out.write("  \t \n");
      out.write(" \n");
      out.write("  \tfunction getLogoutTime(){\n");
      out.write("        var ch  =  (((parseInt(maxage)/(60*1000)).toFixed(2)).toString()).split(\".\");   \n");
      out.write("        if(ch[0]>0){\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+((parseInt(maxage)-(ch[0]*60*1000))/1000)+\" sec(s)\";\n");
      out.write("        }else{\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+(parseInt(maxage)/1000)+\" sec(s)\";   \n");
      out.write("        }\n");
      out.write("    };\n");
      out.write(" }); \n");
      out.write(" \n");
      out.write("$(document).ready (function(){\n");
      out.write("\t$('.effect').click(function(){\n");
      out.write("\t\t$(this).addClass('add-effect');\n");
      out.write("\t});\n");
      out.write("\t$('.effect').blur(function(){\n");
      out.write("\t\t$(this).removeClass('add-effect');\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("label.error{\r\n");
      out.write("\tcolor: #FF0000;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\t<script type=\"text/javascript\" >\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("    \t new JsDatePick({\r\n");
      out.write("\t\t\t\tuseMode:2,\r\n");
      out.write("\t\t\t\ttarget:\"ndaCompletionDate\",\r\n");
      out.write("\t\t\t\tdateFormat:\"%d-%M-%Y\",\r\n");
      out.write("\t\t\t\tlimitToToday:true,\r\n");
      out.write("\t\t\t });\r\n");
      out.write("    \t \r\n");
      out.write("    \t new JsDatePick({\r\n");
      out.write("\t\t\t\tuseMode:2,\r\n");
      out.write("\t\t\t\ttarget:\"estimatedHandoverDate\",\r\n");
      out.write("\t\t\t\tdateFormat:\"%d-%M-%Y\",\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("    \t\r\n");
      out.write("   \t\tvar val = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("   \t\t\r\n");
      out.write("   \t\tvar value='");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("   \t\t//alert(val);\r\n");
      out.write("   \t\tvar isRefurbishmentProject='");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("'; \r\n");
      out.write("   \t//\talert(isRefurbishmentProject);\r\n");
      out.write("   \t\tvar expectedEpcRating='");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'; \r\n");
      out.write("   \t\tvar WindowsUPVCLockable='");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("'; \r\n");
      out.write("   \t\tvar uPVCExternalDoors='");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("   \t\tvar solidWoodInternalDoors='");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar kitchenFacilities='");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar toiletFacilities='");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar isPainted='");
      if (_jspx_meth_c_005fout_005f9(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar isWallsInContemporaryPainted='");
      if (_jspx_meth_c_005fout_005f10(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar isCarpetedThroughout='");
      if (_jspx_meth_c_005fout_005f11(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tvar isOutdoorCommunalDevice='");
      if (_jspx_meth_c_005fout_005f12(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t//alert(WindowsUPVCLockable);\r\n");
      out.write("\t\t//alert(uPVCExternalDoors);\r\n");
      out.write("\t\t//alert(isPainted);\r\n");
      out.write("   \t\t//alert(expectedEpcRating);//alert(val);\r\n");
      out.write("    \tif(val.length != null && val != null && val!=\"\"){\r\n");
      out.write("    \t\t$('#savePDPropertyDetailsAgain').hide();\r\n");
      out.write("\t\t\t$('#UpdateDetailedPDPropertyID').show();\r\n");
      out.write("\t\t\t//alert(value);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif(value==\"true\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t//alert(value);\r\n");
      out.write("\t\t\t$('#ndaStatusYes').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(value==\"false\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t//\talert(value);\r\n");
      out.write("\t\t\t$('#ndaStatusNo').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#ndaStatusYes').attr('checked',false);\r\n");
      out.write("\t\t\t$('#ndaStatusNo').attr('checked',false);\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isRefurbishmentProject==\"true\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isRefurbishmentProjectYes').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(isRefurbishmentProject==\"false\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isRefurbishmentProjectNo').attr('checked',true);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$('#isRefurbishmentProjectYes').attr('checked',false);\r\n");
      out.write("\t\t\t\t$('#isRefurbishmentProjectNo').attr('checked',false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(expectedEpcRating==\"true\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#expectedEpcRatingYes').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if(expectedEpcRating==\"false\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#expectedEpcRatingNo').attr('checked',true);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$('#expectedEpcRatingYes').attr('checked',false);\r\n");
      out.write("\t\t\t\t$('#expectedEpcRatingNo').attr('checked',false);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(WindowsUPVCLockable==\"windows\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isWindowsUPVCLockable').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isWindowsUPVCLockable').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif(uPVCExternalDoors==\"UPVC external doors\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isUPVCExternalDoors').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isUPVCExternalDoors').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(solidWoodInternalDoors==\"Solid wood internal doors\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isSolidWoodInternalDoors').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isSolidWoodInternalDoors').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(kitchenFacilities==\"Kitchen facilities\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isKitchenFacilities').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isKitchenFacilities').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif(toiletFacilities==\"Toilet facilities\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isToiletFacilities').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isToiletFacilities').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isPainted==\"Painted\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isPainted').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isPainted').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isWallsInContemporaryPainted==\"Walls in contemporary colours\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isWallsInContemporaryPainted').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isWallsInContemporaryPainted').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isCarpetedThroughout==\"Carpeted throughout\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isCarpetedThroughout').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isCarpetedThroughout').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(isOutdoorCommunalDevice==\"Outdoor communal space\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isOutdoorCommunalDevice').attr('checked',true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t$('#isOutdoorCommunalDevice').attr('checked',false);\t\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t}\r\n");
      out.write("    \telse\r\n");
      out.write("    \t\t{\r\n");
      out.write("    \t\t$('#savePDPropertyDetailsAgain').show();\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\r\n");
      out.write("    \t});\r\n");
      out.write("   \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <script>\r\n");
      out.write("  $(function() {\r\n");
      out.write("\t    $(\"#registerPropertyDeveloperId\").validate({\r\n");
      out.write("\t        rules: {\r\n");
      out.write("\t            \"firstName\": \"required\",\r\n");
      out.write("\t            \"lastName\": \"required\",\r\n");
      out.write("\t            \"primaryEmailId\": {\r\n");
      out.write("\t                required: true,\r\n");
      out.write("\t                email: true\r\n");
      out.write("\t            },\r\n");
      out.write("\t\t        \"primaryPhoneNumber\": {\r\n");
      out.write("\t\t        \trequired: true,\r\n");
      out.write("\t\t        \t minlength :10,\r\n");
      out.write("\t\t             maxlength : 15\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        \"loginObj.username\": {\r\n");
      out.write("\t\t        \trequired: true,\r\n");
      out.write("\t\t        \tminlength: 3\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        \"loginObj.password\": {\r\n");
      out.write("\t\t        \trequired: true,\r\n");
      out.write("\t\t        \tminlength: 3\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        \"addressObj.city\" : \"required\",\r\n");
      out.write("\t\t        \"addressObj.postCode\" : \"required\",\r\n");
      out.write("\t\t        \"addressObj.addressLine1\" : \"required\",\r\n");
      out.write("\t    },\r\n");
      out.write("\t    messages: {\r\n");
      out.write("\t    \t\"addressObj.city\": {\r\n");
      out.write("\t         required: \"Please Select City.\",\r\n");
      out.write("\t        },\r\n");
      out.write("\t       }\r\n");
      out.write("      });\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  \t$('.close').click(function () {\r\n");
      out.write("  \t    $('#alertId').hide(200);\r\n");
      out.write("    }); \r\n");
      out.write("  </script>\r\n");
      out.write(" <script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("\t  $(function() {\r\n");
      out.write("\t\t    $(\"#secondfPDPropertyDetails\").validate({\r\n");
      out.write("\t\t        rules: {\r\n");
      out.write("\t\t        \t\"isJointVenture\": \r\n");
      out.write("\t\t        \t\t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t\r\n");
      out.write("\t\t        \t\t},\r\n");
      out.write("\t\t        \t\"permissionToCarryOut\" :\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t},\r\n");
      out.write("\t\t        \t\"emergencyContactNo\" : {\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t\t        \t minlength :10,\r\n");
      out.write("\t\t\t        \t number:true,\r\n");
      out.write("\t\t\t             maxlength : 15\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"companyName\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t},\r\n");
      out.write("\t\t        \t\"ndaStatus\" : \"required\",\r\n");
      out.write("\t\t        \t\"ndaCompletionDate\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"expectedRentalLevel\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"accommodationType\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"hmoDeductions\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"haveItsOwnMeteringSupply\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"rateableValue\" :\r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"waterRatesValue\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"numberOfStudioFlates\" :\r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"isRefurbishmentProject\" :\"required\",\r\n");
      out.write("\t\t        \t\"hmoDeductions\" :\r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"haveItsOwnMeteringSupply\" :\r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"rateableValue\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t}\t,\r\n");
      out.write("\t\t        \t\"sustainableFeatures\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t},\r\n");
      out.write("\t\t        \t\"expectedEpcRating\" : \"required\",\r\n");
      out.write("\t\t        \t\"estimatedHandoverDate\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t},\r\n");
      out.write("\t\t        \t\"insurancePolicyNumber\" : \r\n");
      out.write("\t\t        \t{\r\n");
      out.write("\t\t        \t\trequired: true,\r\n");
      out.write("\t\t        \t\t maxlength : 150\r\n");
      out.write("\t\t        \t\t},\r\n");
      out.write("    \t        \t/* \"addressObj.city\": {\r\n");
      out.write("    \t                required: {\r\n");
      out.write("    \t                    depends: function(element) {\r\n");
      out.write("    \t                       if(element.value == 0){\r\n");
      out.write("    \t                    \t   $(\"#cityErrorId\").show();\r\n");
      out.write("    \t                    \t   return false;\r\n");
      out.write("    \t                       }\r\n");
      out.write("    \t                    \t\r\n");
      out.write("    \t                    }\r\n");
      out.write("    \t                }\r\n");
      out.write("    \t            } */\r\n");
      out.write("    \t        \t\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t    messages: {\r\n");
      out.write("\t\t    \t\"addressObj.city\": {\r\n");
      out.write("\t\t         required: \"Please Select City.\",\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t  \r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!--================== Fonts Calling Section =====-->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css' />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/logout-popup-elements.css\"></link> \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/propertyDeveloper.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/property.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#logouthrefId\").click(function(){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t      type: \"get\",\n");
      out.write("\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t      success: function(response){\n");
      out.write("\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t    \t }\n");
      out.write("\t\t\t      },\n");
      out.write("\t\t\t      error:function(){\n");
      out.write("\t\t\t         console.log('Some error is there.');\n");
      out.write("\t\t\t      }\n");
      out.write("\t\t\t  });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<header>\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"span4\">\n");
      out.write("      <div id=\"maskLoader\" class=\"loader\" ></div>\n");
      out.write("        <div class=\"logo\"><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/logo.png\" /></a></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"span8\">\n");
      out.write("        <section class=\"login-sec\"> \n");
      out.write("          <div class=\"user-bt\"><a id=\"logouthrefId\" href=\"#\" >Logout</a></div>\n");
      out.write("          <!-- <div class=\"ban-cot inner-f\">Call&nbsp;Now.&nbsp; 07801892817</div> -->\n");
      out.write("        </section>\n");
      out.write("        <div class=\"clearfix\"></div>\n");
      out.write("        <div class=\"navbar navbar-inverse\">\n");
      out.write("          <div class=\"navbar-inner\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\n");
      out.write("            <div class=\"nav-collapse collapse\">\n");
      out.write("              <ul class=\"nav\">\n");
      out.write("                <li class=\"m-p\" class=\"active\">\n");
      out.write("                <a href=\"#propertyDeveloperProfilePH\" id=\"propertyDeveloperProfilePH\">My Profile</a>                              <!-- done -->\n");
      out.write("                <div class=\"login-drop_1\">\n");
      out.write("                  <ul>\n");
      out.write("                    <li><a href=\"#editPropertyDeveloperPH\" id=\"editPropertyDeveloperPH\">Edit Profile</a></li>                      <!-- done -->\n");
      out.write("                    <li><a href=\"#changePropertyDeveloperPassword\" id=\"changePropertyDeveloperPassword\">Change Password</a></li>   <!-- done -->\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("                </li>\n");
      out.write("                <li><a href=\"#pdProperty\" id=\"pdProperty\">My Properties</a></li>\n");
      out.write("                <li><a href=\"#registerNewPropertyPH\" id=\"registerNewPropertyPH\">Register New Property</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"logoutWindowPopUp\" id=\"logoutWindowId\" onclick = \"check(event)\" style=\"margin-top:7%;\">\n");
      out.write("  <div class=\"popupContact1\">\n");
      out.write("    <div class=\"formClass1\">\n");
      out.write("      <img src= \"");
      out.print(request.getContextPath());
      out.write("/resource/images/cross-image.png\" id=\"close\" style=\"display: none;\"/> \n");
      out.write("      <div class=\"h21\" style=\" padding:15px 35px;\">\n");
      out.write("        <h2 style=\"text-align:center;\">Logout Window</h2>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"pop-p1\">\n");
      out.write("        <p>Your Session is going to expire in</p>\n");
      out.write("        <p id=\"timeLeftId\"> next 15 minutes</p>\n");
      out.write("        <p>Do You want to continue or logout?</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"h21\" style=\"border-top:1px solid #CCC; border-radius:0 0 6px 6px;\">\n");
      out.write("        <button id=\"logoutBtnId\" class=\"button-file1\">Logout</button>\n");
      out.write("        <button id=\"continueBtnId\" class=\"button-file1\" style=\"margin-right:82px;\">Continue</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write(" <span id=\"commonMessageSuccessId\" style=\"display: none; position: absolute; top:10%; margin: 0 auto; min-height: 35px; border-radius:6px; width: 20%; border:1px solid #ccc; left:0; right:0; line-height: 20px;\n");
      out.write("  background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/images/ok-icon.png') no-repeat scroll 25px 10px / 25px 25px #66FF99; z-index:99999; text-align: left; padding: 12px 0 0 58px;\"></span>\n");
      out.write(" <span id=\"commonMessageErrorId\" style=\"display: none; position: absolute; top:10%; margin: 0 auto; min-height: 35px; border-radius:6px; width: 20%; border:1px solid #ccc; left:0; right:0; line-height: 20px;\n");
      out.write("  background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/images/not-ok-icon.png') no-repeat scroll 25px 10px / 25px 25px #FFD6D6; z-index:99999; text-align: left; padding: 12px 0 0 58px;\"></span>\n");
      out.write("  </header>");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<section class=\"banner\" style=\"height:124px;\">\r\n");
      out.write("  <div class=\"flexslider \" style=\"height:150px;\">\r\n");
      out.write("    <ul class=\"slides\">\r\n");
      out.write("      <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/slide1.png\" title=\"\" alt=\"\" /> </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t\t  <div class=\"span-12\">\r\n");
      out.write("\t\t\t  <div class=\"call\">\r\n");
      out.write("\t\t\t \t <div class=\"ban-cot inner-f \">Call&nbsp;Now.&nbsp; 07801892817</div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<section class=\"contaner-b\">\r\n");
      out.write("  <div class=\"container\" id=\"containerId\">\r\n");
      out.write("   <section class=\"contaner-b\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("         <div class=\"span10\">\r\n");
      out.write("         <form id=\"secondfPDPropertyDetails\" name=\"secondfPDPropertyDetails\" novalidate=\"novalidate\">\r\n");
      out.write("          <h1 class=\"heading4 margin-top15\">Property Details</h1>\r\n");
      out.write("          <div>\r\n");
      out.write("            <div class=\"PropertyForm new-form-stra NewFileLine\"> <span>\r\n");
      out.write("              <label>If this is a Joint venture what are the names of the other partners ?</label>\r\n");
      out.write("              <input type=\"text\" name=\"isJointVenture\" id=\"isJointVenture\" class=\"\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsJointVenture()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Do we have your permission to carry out and relevant security and financial check if deemed necessary ?</label>\r\n");
      out.write("              <input type=\"text\" name=\"permissionToCarryOut\"  id=\"permissionToCarryOut\" class=\"\" placeholder=\"\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getPermissionToCarryOut()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Emergency Contact Number ?</label>\r\n");
      out.write("              <input type=\"text\"  name=\"emergencyContactNo\" id=\"emergencyContactNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getEmergencyContactNo()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Company name to be used if any and is it a Limited company ?</label>\r\n");
      out.write("              <input type=\"text\" name=\"companyName\" id=\"companyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getCompanyName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Has an NDA been completed and returned ?</label>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <label class=\"checkRedio\">\r\n");
      out.write("              <input type=\"radio\" name=\"ndaStatus\"  value=\"true\"  id=\"ndaStatusYes\"/>\r\n");
      out.write("              &nbsp;&nbsp;Yes</label>\r\n");
      out.write("              <label class=\"checkRedio\">\r\n");
      out.write("              <input type=\"radio\" name=\"ndaStatus\" value=\"false\" id=\"ndaStatusNo\"/>\r\n");
      out.write("              &nbsp;&nbsp;No</label>\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label> Date NDA was complete:</label>\r\n");
      out.write("              <input type=\"text\" name=\"ndaCompletionDate\" id=\"ndaCompletionDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getNdaCompletionDate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Expected rental level PCM per flat or in the case of an HMO per room PCM ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"£\" name=\"expectedRentalLevel\" id=\"expectedRentalLevel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getExpectedRentalLevel()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Type of accommodation: Studio flat, one bedroom flat ? </label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"\" name=\"accommodationType\" id=\"accommodationType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getAccommodationType()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>In the Case of an HMO what deductions do you make for bills ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"£\" name=\"hmoDeductions\" id=\"hmoDeductions\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getHmoDeductions()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Will each unit have its own metering supply, (please elaborate) ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"\" name=\"haveItsOwnMeteringSupply\" id=\"haveItsOwnMeteringSupply\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getHaveItsOwnMeteringSupply()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Rateable Value ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"£\" name=\"rateableValue\" id=\"rateableValue\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getRateableValue()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Water rates Value ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"£\" name=\"waterRatesValue\" id=\"waterRatesValue\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getWaterRatesValue()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Number of studio flats per this address ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"\" name=\"numberOfStudioFlates\" id=\"numberOfStudioFlates\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getNumberOfStudioFlates()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span >\r\n");
      out.write("              <label>Is this a refurbishment project and if so will the following  be replaced ?</label>\r\n");
      out.write("              <label class=\"checkRedio checkb1\">\r\n");
      out.write("                <input type=\"radio\" name=\"isRefurbishmentProject\" id=\"isRefurbishmentProjectYes\" value=\"true\">\r\n");
      out.write("                &nbsp;&nbsp;Yes</label>\r\n");
      out.write("              <label class=\"checkRedio checkb2\">\r\n");
      out.write("                <input type=\"radio\" name=\"isRefurbishmentProject\" id=\"isRefurbishmentProjectNo\" value=\"false\">\r\n");
      out.write("                &nbsp;&nbsp;No</label>\r\n");
      out.write("              <div class=\"ShowHide Blockbx\">\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isWindowsUPVCLockable\" value=\"windows\" id=\"isWindowsUPVCLockable\">\r\n");
      out.write("                  &nbsp; &nbsp; windows UPVC  lockable,  conforming to building regulations ?</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isUPVCExternalDoors\" value=\"UPVC external doors\" id=\"isUPVCExternalDoors\">\r\n");
      out.write("                  &nbsp; &nbsp; UPVC external doors with multipoint locking mechanism</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isSolidWoodInternalDoors\" value=\"Solid wood internal doors\" id=\"isSolidWoodInternalDoors\">\r\n");
      out.write("                  &nbsp; &nbsp; Solid wood internal doors (front doors fire rated to building regulations standard)</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isKitchenFacilities\" value=\"Kitchen facilities\" id=\"isKitchenFacilities\"> &nbsp; &nbsp; Kitchen facilities - modern cupboards, integrated electric oven, hood and hob</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isToiletFacilities\" value=\"Toilet facilities\" id=\"isToiletFacilities\">\r\n");
      out.write("                  &nbsp; &nbsp; Toilet facilities - White goods (Toilet, shower, basin, chrome taps, etc) Vinyl flooring.</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isPainted\" value=\"Painted\" id=\"isPainted\">\r\n");
      out.write("                  &nbsp; &nbsp; Painted/varnished woodwork/joinery</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isWallsInContemporaryPainted\" value=\"Walls in contemporary colours\" id=\"isWallsInContemporaryPainted\">\r\n");
      out.write("                  &nbsp; &nbsp; Walls in contemporary colours, painted/wallpapered.</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isCarpetedThroughout\" value=\"Carpeted throughout\" id=\"isCarpetedThroughout\">\r\n");
      out.write("                  &nbsp; &nbsp; Carpeted throughout</label>\r\n");
      out.write("                <label class=\"\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"isOutdoorCommunalDevice\" value=\"Outdoor communal space\" id=\"isOutdoorCommunalDevice\">\r\n");
      out.write("                  &nbsp; &nbsp; Outdoor communal space will be pointed, painted and tidied.</label>\r\n");
      out.write("                <p class=\"pp\">Please give as much information as possible as this list is an aid for ones memory.</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>What Sustainable features will there be ?</label>\r\n");
      out.write("              <input type=\"text\"  placeholder=\"\" name=\"sustainableFeatures\" id=\"sustainableFeatures\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getSustainableFeatures()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Expected EPC Rating after works are completed or new build ?</label>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <label class=\"checkRedio\">\r\n");
      out.write("                <input type=\"radio\" name=\"expectedEpcRating\" value=\"true\" id=\"expectedEpcRatingYes\">\r\n");
      out.write("                &nbsp;&nbsp;Yes</label>\r\n");
      out.write("              <label class=\"checkRedio\">\r\n");
      out.write("                <input type=\"radio\" name=\"expectedEpcRating\" value=\"false\" id=\"expectedEpcRatingNo\">\r\n");
      out.write("                &nbsp;&nbsp;No</label>\r\n");
      out.write("              </span> <!--<span>\r\n");
      out.write("              <label>Please provide details of the building specification, Word document or pdf ?</label>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("              <input type=\"file\" value=\"\" style=\"margin-top:5px;\" />\r\n");
      out.write("              </span>--> <span>\r\n");
      out.write("              <label>Estimated handover date:</label>\r\n");
      out.write("              <input type=\"text\" name=\"estimatedHandoverDate\" id=\"estimatedHandoverDate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getEstimatedHandoverDate()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly=\"readonly\">\r\n");
      out.write("              </span> <span>\r\n");
      out.write("              <label>Buildings insurance policy number  and start date ?</label>\r\n");
      out.write("              <input type=\"text\"  name=\"insurancePolicyNumber\" id=\"insurancePolicyNumber\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getInsurancePolicyNumber()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("              </span>\r\n");
      out.write("              <span>\r\n");
      out.write("              <label>Additinational info </label>\r\n");
      out.write("              <textarea></textarea>\r\n");
      out.write("              </span>\r\n");
      out.write("              <div class=\"clearfix\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a class=\"backbtnnew\" style=\"margin-top:15px; float:left;\" href=\"redirectCompleteProperties.htm\">Back</a>\r\n");
      out.write("          <input type=\"button\" style=\"display:none;\" value=\"Update and Continue\" class=\"regis-co\" id=\"UpdateDetailedPDPropertyID\">\r\n");
      out.write("          <input type=\"button\" value=\"Submit and Continue\" class=\"regis-co\" id=\"savePDPropertyDetailsAgain\">\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      <div class=\"span2\"> <img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/banner.png\" width=\"160\" height=\"600\" class=\"ad-ban\" /> </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write(" ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(71,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(73,16) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getNdaStatus()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(75,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsRefurbishmentProject()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(77,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getExpectedEpcRating()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(78,30) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsWindowsUPVCLockable()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(79,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsUPVCExternalDoors()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f6.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(80,33) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsSolidWoodInternalDoors()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
    if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f7.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(81,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsKitchenFacilities()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
    if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f8.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(82,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsToiletFacilities()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
    if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f9 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f9.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f9.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(83,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f9.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsPainted()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f9 = _jspx_th_c_005fout_005f9.doStartTag();
    if (_jspx_th_c_005fout_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f9);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f10 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f10.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f10.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(84,36) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f10.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsWallsInContemporaryPainted()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f10 = _jspx_th_c_005fout_005f10.doStartTag();
    if (_jspx_th_c_005fout_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f10);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f10);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f11 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f11.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f11.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(85,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f11.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsCarpetedThroughout()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f11 = _jspx_th_c_005fout_005f11.doStartTag();
    if (_jspx_th_c_005fout_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f11);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f11);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f12 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f12.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f12.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(86,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f12.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj.getIsOutdoorCommunalDevice()}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f12 = _jspx_th_c_005fout_005f12.doStartTag();
    if (_jspx_th_c_005fout_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f12);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f12);
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/detailedRegistrationPropertyDeveloper.jsp(561,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wordPressUrl}/sub-footer/", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }
}
