/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-15 11:35:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user.propertyDeveloper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerPropertyDeveloper_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t<link href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/sumoselect.css\" rel=\"stylesheet\" />\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.sumoselect.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/propertyDeveloper.js\"></script> \n");
      out.write("\t\n");
      out.write("<style>\n");
      out.write("label.error{\n");
      out.write("\tcolor: #FF0000;\n");
      out.write("\tfloat: right;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("\t    $(document).ready(function(){\n");
      out.write("\t    \t $.getJSON(contextPath+\"/register/loadCitiesForLandlord.htm\", function(options) {\n");
      out.write("\t     \t      var dropdown = $('#landlordCity');\n");
      out.write("\t     \t      dropdown.empty();\n");
      out.write("\t     \t      if (options) {\n");
      out.write("\t     \t    \t  var opts = options.data;\n");
      out.write("\t     \t    \t dropdown.append($('<option/>').val('').text('Select City'));\n");
      out.write("\t     \t          $.each(opts, function(id, city) {\n");
      out.write("\t     \t        \t  dropdown.append($('<option/>').val(this.id).text(this.city));\n");
      out.write("\t     \t          });\n");
      out.write("\t     \t      }\n");
      out.write("\t     \t });\n");
      out.write("\t    \t \n");
      out.write("\t    \t    $(\"#userName\").blur(function(){\n");
      out.write("\t    \t    \tconsole.log(validateUser());\n");
      out.write("\t    \t    \t\n");
      out.write("\t    \t    });\n");
      out.write("\t    });\n");
      out.write("\t    \n");
      out.write("\t    function validateUser(){\n");
      out.write("\t    \tvar name = $(\"#userName\").val();\n");
      out.write("\t    \tif(name.trim()){\n");
      out.write("    \t    $(\"#lbl\").html(\"\");\n");
      out.write("\t    \t$.ajax({\n");
      out.write("\t    \t\turl:contextPath+\"/register/validateUser.htm\",\n");
      out.write("        \t\tmethod: \"Post\",\n");
      out.write("        \t\tdataType: \"json\",\n");
      out.write("        \t\tdata : {user : name},\n");
      out.write("        \t\tsuccess:function(data){\n");
      out.write("        \t\t\tif(data.success == true){\n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").removeAttr('disabled');\n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").css('cursor', 'pointer');\n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").css('background', '#FF0000');\n");
      out.write("        \t\t\t\tconsole.log(\"Username Available\");\n");
      out.write("        \t\t\t}\n");
      out.write("        \t\t\tif(data.success == false){\t  \n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").attr('disabled','true');\n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").css('cursor', 'no-drop');\n");
      out.write("        \t\t\t\t$(\"#propertyDeveloperSubmitId\").css('background', '#707070');\n");
      out.write("        \t\t\t\tconsole.log(\"Username not available\");\n");
      out.write("        \t\t\t\t$(\"#lbl\").html(\"Username Not Available\");\n");
      out.write("        \t\t\t}\n");
      out.write("        \t    },\n");
      out.write("        \t   error: function(error){\n");
      out.write("    \t\t\t\tconsole.log(\"Can't Validate the Username\");\n");
      out.write("    \t  \t      }\n");
      out.write("           });\n");
      out.write("\t    }\n");
      out.write("\t }\n");
      out.write("   </script>\n");
      out.write("  <script>\n");
      out.write("  $(function() {\n");
      out.write("\t    $(\"#registerPropertyDeveloperId\").validate({\n");
      out.write("\t        rules: {\n");
      out.write("\t            \"firstName\": \"required\",\n");
      out.write("\t            \"lastName\": \"required\",\n");
      out.write("\t            \"primaryEmailId\": {\n");
      out.write("\t                required: true,\n");
      out.write("\t                email: true\n");
      out.write("\t            },\n");
      out.write("\t\t        \"primaryPhoneNumber\": {\n");
      out.write("\t\t        \trequired: true,\n");
      out.write("\t\t        \t minlength :10,\n");
      out.write("\t\t             maxlength : 15\n");
      out.write("\t\t        },\n");
      out.write("\t\t        \"loginObj.username\": {\n");
      out.write("\t\t        \trequired: true,\n");
      out.write("\t\t        \tminlength: 3\n");
      out.write("\t\t        },\n");
      out.write("\t\t        \"loginObj.password\": {\n");
      out.write("\t\t        \trequired: true,\n");
      out.write("\t\t        \tminlength: 3\n");
      out.write("\t\t        },\n");
      out.write("\t\t        \"addressObj.city\" : \"required\",\n");
      out.write("\t\t        \"addressObj.postCode\" : \"required\",\n");
      out.write("\t\t        \"addressObj.addressLine1\" : \"required\",\n");
      out.write("\t    },\n");
      out.write("\t    messages: {\n");
      out.write("\t    \t\"addressObj.city\": {\n");
      out.write("\t         required: \"Please Select City.\",\n");
      out.write("\t        },\n");
      out.write("\t       }\n");
      out.write("      });\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  \t$('.close').click(function () {\n");
      out.write("  \t    $('#alertId').hide(200);\n");
      out.write("    }); \n");
      out.write("  </script>\n");
      out.write("<div class=\"row\">\n");
      out.write("      <div class=\"span10\">\n");
      out.write("      <span id=\"commonMessageErrorId\" style=\"display: none; position: absolute; top:50%; margin: 0 auto; min-height: 35px; border-radius:6px; width: 20%; border:1px solid #ccc; left:0; right:0; line-height: 20px;\n");
      out.write("  \t\tbackground: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/images/not-ok-icon.png') no-repeat scroll 25px 10px / 25px 25px #FFD6D6; z-index:99999; text-align: left; padding: 12px 0 0 58px;\"></span>\n");
      out.write("        <h1 class=\"heading2 margin-top15\">Property Developer Registration</h1>\n");
      out.write("        \n");
      out.write("        <div id=\"alertId\" class=\"alert alert-block alert-success fade in\" hidden=\"true\" >\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-success\" animation=\"true\" id=\"errorId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"rg-p\">\n");
      out.write("          <form  name=\"registerPropertyDeveloper\" id=\"registerPropertyDeveloperId\" autocomplete=\"on\">\n");
      out.write("            <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"regis\">\n");
      out.write("\t            <tr>\n");
      out.write("\t              <td><label>First Name</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your first name\" class=\"\" name=\"firstName\" id=\"\" value=\"\" maxlength=\"150\" /></td>\n");
      out.write("\t              <td><label>Last Name</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your last name\" class=\"\" name=\"lastName\" id=\"\" value=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t            </tr>\n");
      out.write("\t            <tr>\n");
      out.write("\t              <td><label>Primary Email Id</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your email id\" class=\"\" name=\"primaryEmailId\" id=\"\" value=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t              <td><label>Secondary Email Id</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your email id\" class=\"\" name=\"secondaryEmailId\" id=\"\"  maxlength=\"150\"/></td>\n");
      out.write("\t            </tr>\n");
      out.write("\t             <tr>\n");
      out.write("\t              <td><label>Primary Contact Number</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your contact number\" class=\"\" name=\"primaryPhoneNumber\" id=\"\" value=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t              <td><label>Secondary Contact Number</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter your contact number\" class=\"\" name=\"secondaryPhoneNumber\" id=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t            </tr>\n");
      out.write("\t            <tr>\n");
      out.write("\t              <td><label>User Name</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"Enter the field\" class=\"\" name=\"loginObj.username\" id=\"userName\" value=\"\" maxlength=\"150\" autocomplete=\"off\"/><label id=\"lbl\" style=\"float: right; color:red;\"></label></td>\n");
      out.write("\t               <td><label>Password</label>\n");
      out.write("\t                <input type=\"password\" placeholder=\"Enter your password\" class=\"\" name=\"loginObj.password\" id=\"\" value=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t            </tr>\n");
      out.write("\t             <tr>\n");
      out.write("\t             <td><label>Address Line1</label>\n");
      out.write("\t            \t <input type=\"text\" placeholder=\"Type your address line 1\"  class=\"\" name=\"addressObj.addressLine1\" id=\"\" value=\"\" maxlength=\"150\" /></td>\n");
      out.write("\t              <td><label>Address Line2</label>\n");
      out.write("\t              \t  <input type=\"text\" placeholder=\"Type your address line 1\"  class=\"\" name=\"addressObj.addressLine2\" id=\"\" value=\"\" maxlength=\"150\"/></td>\n");
      out.write("\t            </tr>\n");
      out.write("\t            <tr>\n");
      out.write("\t          \t\t <td>\n");
      out.write("\t          \t\t\t<label>Choose City</label>\n");
      out.write("\t          \t\t\t<select name=\"addressObj.city\" id=\"landlordCity\">\n");
      out.write("\t                  </select></td>\n");
      out.write("\t              <td><label>County</label>\n");
      out.write("                  <input type=\"text\" placeholder=\"Enter your County\" class=\"\" name=\"addressObj.county\" id=\"\" value=\"\" maxlength=\"150\" autocomplete=\"on\"/></td>    \n");
      out.write("\t           \t </tr>\n");
      out.write("              <tr>\n");
      out.write("              <td><label>PostCode</label>\n");
      out.write("\t                <input type=\"text\" placeholder=\"PostCode\" class=\"\" name=\"addressObj.postCode\" id=\"\" value=\"\" maxlength=\"150\" autocomplete=\"on\" /></td>\n");
      out.write("                <td><label>Land Mark(optional)</label>\n");
      out.write("            \t <input type=\"text\" placeholder=\"Any Landmark\"  class=\"\" name=\"addressObj.landmark\" id=\"\" maxlength=\"150\"/></td>\n");
      out.write("                <td><input type=\"button\" id=\"propertyDeveloperSubmitId\" style=\"margin:0;\" value=\"Register Now\" /></td>\n");
      out.write("              </tr>\n");
      out.write("            </table>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"span2\"> <img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/banner.png\" width=\"160\" height=\"600\" class=\"ad-ban\" /> </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
