/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-15 11:41:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user.propertyDeveloper;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewAdminUploadedDocs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/common/common.jsp", Long.valueOf(1436246875542L));
    _jspx_dependants.put("/WEB-INF/jsp/user/propertyDeveloper/pdheader.jsp", Long.valueOf(1436246877146L));
    _jspx_dependants.put("/WEB-INF/jsp/user/propertyDeveloper/adminDocs.jsp", Long.valueOf(1436879432821L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>The No Voids Man</title>\n");
      out.write("<!-- ---------------- Style Sheet --------------------------------->\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/style.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap-responsive.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/responsive-media-queries.css\" />\n");
      out.write("<link media=\"screen\" rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/ui-progress-bar.css\"/>\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" target=\"_blank\" media=\"screen\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/popup.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/jquery.remodal.css\" />\n");
      out.write("<!-- ---------------- JavaScript --------------------------------->\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-transition.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-dropdown.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-collapse.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/featherlight.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/form2Object.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/json2.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/logout-popup.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("(function() {\n");
      out.write("\t  // Union of Chrome, Firefox, IE, Opera, and Safari console methods\n");
      out.write("\t  var methods = [\"assert\", \"assert\", \"cd\", \"clear\", \"count\", \"countReset\",\n");
      out.write("\t    \"debug\", \"dir\", \"dirxml\", \"dirxml\", \"dirxml\", \"error\", \"error\", \"exception\",\n");
      out.write("\t    \"group\", \"group\", \"groupCollapsed\", \"groupCollapsed\", \"groupEnd\", \"info\",\n");
      out.write("\t    \"info\", \"log\", \"log\", \"markTimeline\", \"profile\", \"profileEnd\", \"profileEnd\",\n");
      out.write("\t    \"select\", \"table\", \"table\", \"time\", \"time\", \"timeEnd\", \"timeEnd\", \"timeEnd\",\n");
      out.write("\t    \"timeEnd\", \"timeEnd\", \"timeStamp\", \"timeline\", \"timelineEnd\", \"trace\",\n");
      out.write("\t    \"trace\", \"trace\", \"trace\", \"trace\", \"warn\"];\n");
      out.write("\t  var length = methods.length;\n");
      out.write("\t  var console = (window.console = window.console || {});\n");
      out.write("\t  var method;\n");
      out.write("\t  var noop = function() {};\n");
      out.write("\t  while (length--) {\n");
      out.write("\t    method = methods[length];\n");
      out.write("\t    // define undefined methods as noops to prevent errors\n");
      out.write("\t    if (!console[method])\n");
      out.write("\t      console[method] = noop;\n");
      out.write("\t  }\n");
      out.write("\t})();\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("    var contextPath ;\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tcontextPath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t\t\t$(\"#logoutBtnId\").click(function(){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t\t      type: \"get\",\n");
      out.write("\t\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t\t      success: function(response){\n");
      out.write("\t\t\t\t    \t  \n");
      out.write("\t\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t\t    \t }\n");
      out.write("\t\t\t\t      },\n");
      out.write("\t\t\t\t      error:function(){\n");
      out.write("\t\t\t\t    \t  console.log('Some error is there.');\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t  });\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#continueBtnId\").click(function(){\n");
      out.write("\t\t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/home.htm\";\n");
      out.write("\t\t\t});\n");
      out.write("\t\tconsole.log(contextPath);\n");
      out.write("\t\t});\n");
      out.write("\tfunction getContextPath() {\n");
      out.write("\t\t   return \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t  var homemaxage = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${homemaxage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t  \n");
      out.write("\t var stop = true;\n");
      out.write("  \t var maxage =\"\";\n");
      out.write("  \t var name = \"maxage\" + \"=\";\n");
      out.write("  \t var intval = 1000;\n");
      out.write("  \t \n");
      out.write("  \t setInterval(function (){\n");
      out.write("  \t\t \n");
      out.write("  \t   \t var cdata = document.cookie.split(';');\n");
      out.write("        // console.log(cdata);\n");
      out.write("         \n");
      out.write("  \t   \t  for(var i=0; i<cdata.length; i++){\n");
      out.write("\n");
      out.write("  \t   \t  \tvar c = cdata[i].trim();\n");
      out.write("  \t   \t  \tif (c.indexOf(\"maxage\")==0){\n");
      out.write("  \t   \t  \t\t\tmaxage = c.substring(name.length,c.length);\n");
      out.write("  \t   \t  \t\t\tif(maxage == homemaxage){\n");
      out.write("  \t   \t  \t\t\t\tdocument.cookie ='maxage='+maxage;\n");
      out.write("  \t   \t  \t\t\t\tstop = true;\n");
      out.write("  \t   \t  \t\t\t}\n");
      out.write("  \t   \t  \t    \tbreak;\t\n");
      out.write("  \t   \t \t\t}\n");
      out.write("  \t   \t  }\n");
      out.write("  \t   \t \n");
      out.write("  \t   \t  if(maxage != null && maxage!=\"\"){\n");
      out.write("  \t   \t\t  maxage = parseInt(maxage)-1000;\n");
      out.write("  \t   \t\t  if(parseInt(maxage) <= 0.00){\n");
      out.write("  \t   \t\t\t  document.cookie =name+\";expires=\"+new Date();\n");
      out.write("  \t   \t\t\t$.ajax({\n");
      out.write("    \t\t\t\t  url: contextPath+\"/home/applicationLogout.htm\",\n");
      out.write("    \t\t\t      type: \"GET\",\n");
      out.write("    \t\t\t      dataType : \"json\",\n");
      out.write("    \t\t\t      success: function(response){\n");
      out.write("    \t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("    \t\t\t    \t\twindow.location.href = contextPath+'/j_spring_security_logout';\n");
      out.write("    \t\t\t    \t }\n");
      out.write("    \t\t\t      },\n");
      out.write("    \t\t\t      error:function(){\n");
      out.write("    \t\t\t         console.log('Some error is there.');\n");
      out.write("    \t\t\t      }\n");
      out.write("    \t\t\t  });\n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t  }\n");
      out.write("  \t   \t\t  document.cookie ='maxage='+maxage;\n");
      out.write("  \t     \t\t  if(parseInt(maxage) < (2*60*1000)){\n");
      out.write("  \t     \t\t\t  if(stop){\n");
      out.write("  \t     \t\t\t\t var logoutStr = getLogoutTime();\n");
      out.write("  \t     \t\t\t\tconsole.log(logoutStr);\n");
      out.write("  \t     \t\t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t\t\tlogoutPopUp('bodyId', 'logoutWindowId');\n");
      out.write("  \t     \t\t\t\tstop =false;\n");
      out.write("  \t     \t\t\t\t\n");
      out.write("  \t     \t\t\t  }\n");
      out.write("  \t     \t\t\t var logoutStr = getLogoutTime();\n");
      out.write("\t     \t\t\t\tconsole.log(\"appending : \" + logoutStr);\n");
      out.write("\t     \t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t  }\n");
      out.write("  \t   \t  }\n");
      out.write("  \t    }, intval);\n");
      out.write("  \t \n");
      out.write(" \n");
      out.write("  \tfunction getLogoutTime(){\n");
      out.write("        var ch  =  (((parseInt(maxage)/(60*1000)).toFixed(2)).toString()).split(\".\");   \n");
      out.write("        if(ch[0]>0){\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+((parseInt(maxage)-(ch[0]*60*1000))/1000)+\" sec(s)\";\n");
      out.write("        }else{\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+(parseInt(maxage)/1000)+\" sec(s)\";   \n");
      out.write("        }\n");
      out.write("    };\n");
      out.write(" }); \n");
      out.write(" \n");
      out.write("$(document).ready (function(){\n");
      out.write("\t$('.effect').click(function(){\n");
      out.write("\t\t$(this).addClass('add-effect');\n");
      out.write("\t});\n");
      out.write("\t$('.effect').blur(function(){\n");
      out.write("\t\t$(this).removeClass('add-effect');\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/landlord.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/property.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- ---------------- flexslider --------------------------------->\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.flexslider.js\"></script>\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\n");
      out.write("  $(window).load(function() {\n");
      out.write("    $('.flexslider').flexslider({\n");
      out.write("          animation: \"fade\",  // slide or fade\n");
      out.write("          controlsContainer: \".flex-container\" // the container that holds the flexslider\n");
      out.write("          //checked...\n");
      out.write("          \n");
      out.write("    });\n");
      out.write("  });\n");
      out.write("</script>\n");
      out.write("<!--================== Fonts Calling Section =====-->\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css' />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write(" ");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/logout-popup-elements.css\"></link> \n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/propertyDeveloper.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/property.js\"></script>\n");
      out.write("<script>\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t\n");
      out.write("\t\t$(\"#logouthrefId\").click(function(){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t      type: \"get\",\n");
      out.write("\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t      success: function(response){\n");
      out.write("\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t    \t }\n");
      out.write("\t\t\t      },\n");
      out.write("\t\t\t      error:function(){\n");
      out.write("\t\t\t         console.log('Some error is there.');\n");
      out.write("\t\t\t      }\n");
      out.write("\t\t\t  });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("</script>\n");
      out.write("<header>\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"span4\">\n");
      out.write("      <div id=\"maskLoader\" class=\"loader\" ></div>\n");
      out.write("        <div class=\"logo\"><a href=\"#\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/logo.png\" /></a></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"span8\">\n");
      out.write("        <section class=\"login-sec\"> \n");
      out.write("          <div class=\"user-bt\"><a id=\"logouthrefId\" href=\"#\" >Logout</a></div>\n");
      out.write("          <!-- <div class=\"ban-cot inner-f\">Call&nbsp;Now.&nbsp; 07801892817</div> -->\n");
      out.write("        </section>\n");
      out.write("        <div class=\"clearfix\"></div>\n");
      out.write("        <div class=\"navbar navbar-inverse\">\n");
      out.write("          <div class=\"navbar-inner\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\n");
      out.write("            <div class=\"nav-collapse collapse\">\n");
      out.write("              <ul class=\"nav\">\n");
      out.write("                <li class=\"m-p\" class=\"active\">\n");
      out.write("                <a href=\"#propertyDeveloperProfilePH\" id=\"propertyDeveloperProfilePH\">My Profile</a>                              <!-- done -->\n");
      out.write("                <div class=\"login-drop_1\">\n");
      out.write("                  <ul>\n");
      out.write("                    <li><a href=\"#editPropertyDeveloperPH\" id=\"editPropertyDeveloperPH\">Edit Profile</a></li>                      <!-- done -->\n");
      out.write("                    <li><a href=\"#changePropertyDeveloperPassword\" id=\"changePropertyDeveloperPassword\">Change Password</a></li>   <!-- done -->\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("                </li>\n");
      out.write("                <li><a href=\"#pdProperty\" id=\"pdProperty\">My Properties</a></li>\n");
      out.write("                <li><a href=\"#registerNewPropertyPH\" id=\"registerNewPropertyPH\">Register New Property</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"logoutWindowPopUp\" id=\"logoutWindowId\" onclick = \"check(event)\" style=\"margin-top:7%;\">\n");
      out.write("  <div class=\"popupContact1\">\n");
      out.write("    <div class=\"formClass1\">\n");
      out.write("      <img src= \"");
      out.print(request.getContextPath());
      out.write("/resource/images/cross-image.png\" id=\"close\" style=\"display: none;\"/> \n");
      out.write("      <div class=\"h21\" style=\" padding:15px 35px;\">\n");
      out.write("        <h2 style=\"text-align:center;\">Logout Window</h2>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"pop-p1\">\n");
      out.write("        <p>Your Session is going to expire in</p>\n");
      out.write("        <p id=\"timeLeftId\"> next 15 minutes</p>\n");
      out.write("        <p>Do You want to continue or logout?</p>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"h21\" style=\"border-top:1px solid #CCC; border-radius:0 0 6px 6px;\">\n");
      out.write("        <button id=\"logoutBtnId\" class=\"button-file1\">Logout</button>\n");
      out.write("        <button id=\"continueBtnId\" class=\"button-file1\" style=\"margin-right:82px;\">Continue</button>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write(" <span id=\"commonMessageSuccessId\" style=\"display: none; position: absolute; top:10%; margin: 0 auto; min-height: 35px; border-radius:6px; width: 20%; border:1px solid #ccc; left:0; right:0; line-height: 20px;\n");
      out.write("  background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/images/ok-icon.png') no-repeat scroll 25px 10px / 25px 25px #66FF99; z-index:99999; text-align: left; padding: 12px 0 0 58px;\"></span>\n");
      out.write(" <span id=\"commonMessageErrorId\" style=\"display: none; position: absolute; top:10%; margin: 0 auto; min-height: 35px; border-radius:6px; width: 20%; border:1px solid #ccc; left:0; right:0; line-height: 20px;\n");
      out.write("  background: url('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/resource/images/not-ok-icon.png') no-repeat scroll 25px 10px / 25px 25px #FFD6D6; z-index:99999; text-align: left; padding: 12px 0 0 58px;\"></span>\n");
      out.write("  </header>");
      out.write("\n");
      out.write("<div class=\"clearfix\"></div>\n");
      out.write("<section class=\"banner\" style=\"height:124px;\">\n");
      out.write("  <div class=\"flexslider \" style=\"height:150px;\">\n");
      out.write("    <ul class=\"slides\">\n");
      out.write("      <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/slide1.png\" title=\"\" alt=\"\" /> </li>\n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("  <div class=\"container\">\n");
      out.write("\t  <div class=\"row\">\n");
      out.write("\t\t  <div class=\"span-12\">\n");
      out.write("\t\t\t  <div class=\"call\">\n");
      out.write("\t\t\t \t <div class=\"ban-cot inner-f \">Call&nbsp;Now.&nbsp; 07801892817</div>\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t  </div>\n");
      out.write("\t  </div>\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("<div class=\"clearfix\"></div>\n");
      out.write("<section class=\"contaner-b\">\n");
      out.write("  <div class=\"container\" id=\"containerId\">\n");
      out.write("    ");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("$(\"#BackAdminPdDocument\")\n");
      out.write(".click(\n");
      out.write("\t\tfunction() {\n");
      out.write("\t\t\twindow.location.href = contextPath\n");
      out.write("\t\t\t\t\t+ \"/propertyDeveloper/redirectCompleteProperties.htm\";\n");
      out.write("\t\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" <section class=\"contaner-b\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("   \n");
      out.write(" \n");
      out.write("    <div class=\"row\">\n");
      out.write("  \n");
      out.write("      <div class=\"span12\">\n");
      out.write("        <h1 class=\"heading4 margin-top15\">Suggested Documents Uploaded By Admin </h1>\n");
      out.write("       <div id=\"documents\" class=\"tab_content1 rg-p innew tabs-file\" style=\"padding: 18px 11px!important; margin-top: 0px!important;\">\n");
      out.write("\t\t  \n");
      out.write("\t\t  <!-- <h1> Documents</h1> -->\n");
      out.write("\t\t  \n");
      out.write("\t\t  <table class=\"UploadTable\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" id=\"documentId\"> \n");
      out.write("\t\t  \t\t<thead>\n");
      out.write("\t\t  \t\t<tr>\n");
      out.write("\t\t \t\t <th>Name</th>\n");
      out.write("                 <th>Uploaded On</th>\n");
      out.write("                 <th>Status</th>\n");
      out.write("                 <th>Action</th>\n");
      out.write("                 <th>Description</th>\n");
      out.write("                 </tr>\n");
      out.write("\t\t  \t\t</thead>\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t  </table>\n");
      out.write("\t\t  \n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div style=\"margin:20px 0;\" class=\"button\">\n");
      out.write("      <button  id=\"BackAdminPdDocument\">Back</button>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</section>");
      out.write("\n");
      out.write("  </div>\n");
      out.write("</section>\n");
      out.write("<div class=\"clearfix\"></div>\n");
      out.write(" ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/adminDocs.jsp(38,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docList != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                 \t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("                 ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/user/propertyDeveloper/adminDocs.jsp(39,18) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("docObj");
    // /WEB-INF/jsp/user/propertyDeveloper/adminDocs.jsp(39,18) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/user/propertyDeveloper/adminDocs.jsp(39,18) '${docList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${docList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t                 <tr>\n");
          out.write("\t\t                 <td> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docObj.getFileName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\n");
          out.write("\t\t\t             <td> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docObj.getCreatedOn()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</td>\n");
          out.write("\t\t\t             <td> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docObj.getStatusStr()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\n");
          out.write("\t\t\t             \n");
          out.write("\t\t\t             <td><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/propertyDeveloper/downAdminDocuments.htm?documentId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docObj.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" style=\"margin-top: 5px;\"><img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/resource/images/downloadIcon.png\"></a>\n");
          out.write("\t\t\t             &nbsp;&nbsp;&nbsp;&nbsp;</td>\n");
          out.write("\t\t\t             <td> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${docObj.getDescription()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" </td>\n");
          out.write("\t\t\t             </tr>\n");
          out.write("                 \t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/jsp/user/propertyDeveloper/viewAdminUploadedDocs.jsp(76,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wordPressUrl}/sub-footer/", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }
}
