/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-07 06:00:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/jsp/user/home/home.jsp", Long.valueOf(1436246877123L));
    _jspx_dependants.put("/WEB-INF/jsp/user/home/footer.jsp", Long.valueOf(1436246876812L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>The No Voids Man</title>\r\n");
      out.write("<!-- ---------------- Style Sheet --------------------------------->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/style.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/bootstrap-responsive.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/responsive-media-queries.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/jsDatePick_ltr.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------- JavaScript ------------------------------------>\r\n");
      out.write("   \t \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function getContextPath() {\r\n");
      out.write("\t   return \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t}\r\n");
      out.write("var contextPath = getContextPath();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-transition.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-dropdown.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap-collapse.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/featherlight.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/bootstrap.min.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jsDatePick.jquery.min.1.3.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/form2Object.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/json2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/landlord.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/contractor.js\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/propertyDeveloper.js\"></script> \r\n");
      out.write("<!-- ---------------- flexslider --------------------------------->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.flexslider.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\">\r\n");
      out.write("  $(window).load(function() {\r\n");
      out.write("    $('.flexslider').flexslider({\r\n");
      out.write("          animation: \"fade\",  // slide or fade\r\n");
      out.write("          controlsContainer: \".flex-container\" // the container that holds the flexslider\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("  \r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("\t  //var abc = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t  \t\t\t$('.close').click(function () {\r\n");
      out.write("\t\t  \t    $('#alertSuccessId').hide(200);\r\n");
      out.write("\t\t  \t    $('#alertErrorId').hide(200);\r\n");
      out.write("\t\t    }); \r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  //\t$('#alertSuccessId').hide(5000);\r\n");
      out.write("\t\t//\t$('#alertErrorId').hide(5000);\r\n");
      out.write(" }); \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("\t  \t$(\".featherlight-close\").bind('style', function() {\r\n");
      out.write("\t  \t  console.log('bind........');\r\n");
      out.write("\t  \t});\r\n");
      out.write("  \t\t$(\".featherlight-close\").click(function() {\r\n");
      out.write("  \t\t\tconsole.log('clicked........');\r\n");
      out.write("  \t\t});\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("<!--================== Fonts Calling Section =====-->\r\n");
      out.write("<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,200,200italic,300,300italic,400italic,600,600italic,700,700italic,900' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
 String paramName = request.getServletContext().getInitParameter("wordPressUrl");
	if(paramName != null && paramName.length() > 0){
		response.sendRedirect(paramName);   	
	}
	
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  <div class=\"cooki\" id=\"cookiesDivisionId\">\r\n");
      out.write("        <p><strong>Information about our use of cookies </strong>  Our website uses cookies to distinguish you from other users of our website. This helps us to provide..... <span>\r\n");
      out.write("        <a href=\"#containerId\" id=\"readCookiesId\">Read More</a>  |  <a style=\"cursor: pointer!important;\" id=\"cookiesAgreeId\">Agree</a> <img id=\"cookiesImgId\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/small-ico.png\" alt=\"\" /></span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"avoid-video\">\"THE NO VOIDS MAN\", if you want to avoid voids then don't avoid me</div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"span4\">\r\n");
      out.write("        <div class=\"logo\"><a href=\"login.htm\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/logo.png\" /></a></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"span8\">\r\n");
      out.write("        <section class=\"login-sec\">\r\n");
      out.write("          <div class=\"user-bt ano-r\"><a href=\"#\">Register</a>\r\n");
      out.write("            <div class=\"login-drop\">\r\n");
      out.write("              <ul>\r\n");
      out.write("                 <li><a id=\"regLandlordhref\" href=\"#regLandlordhref\">Landlord</a></li>\r\n");
      out.write("                <li><a id=\"regContractorhref\" href=\"#regContractorhref\">Contractor</a></li>\r\n");
      out.write("                 <li><a id=\"regPropDeveloperhref\" href=\"#regPropDeveloperhref\">Property Developer</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"user-bt\"><a href=\"#\" data-featherlight=\"#fl1\">Login</a></div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("        <div class=\"navbar navbar-inverse\">\r\n");
      out.write("          <div class=\"navbar-inner\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\"> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> </button>\r\n");
      out.write("            <div class=\"nav-collapse collapse\">\r\n");
      out.write("              <ul class=\"nav\">\r\n");
      out.write("                <li class=\"active\" id=\"homeliId\"><a href=\"login.htm\" id=\"homeId\">Home</a></li>\r\n");
      out.write("                <li id=\"aboutUsliId\"><a href=\"#aboutUsId\" id=\"aboutUsId\">About Us</a></li>\r\n");
      out.write("                <li id=\"contactUsliId\"><a href=\"#contactUsId\" id=\"contactUsId\">Contact Us</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<section class=\"banner\">\r\n");
      out.write("  <div class=\"flexslider\">\r\n");
      out.write("    <ul class=\"slides\">\r\n");
      out.write("      <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/slide1.png\" title=\"\" alt=\"\" /> </li>\r\n");
      out.write("      <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/slide2.png\" title=\"\" alt=\"\" /> </li>\r\n");
      out.write("      <li><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/slide1.png\" title=\"\" alt=\"\" /> </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("<section class=\"contaner-b\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container\" id=\"containerId\">\r\n");
      out.write("   \t ");
      out.write(" \n");
      out.write(" <div class=\"row\">\n");
      out.write("      <div class=\"span12\">\n");
      out.write("        <div class=\"box-for\">\n");
      out.write("          <div class=\"img-bx\"> <img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/landlord.jpg\" width=\"595\" height=\"347\" />\n");
      out.write("            <div class=\"cut-im\"></div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"cont-box\">\n");
      out.write("            <h1 class=\"heading1\">Landlord</h1>\n");
      out.write("            <article>\n");
      out.write("              <p>Dear landlord if you're here, then it could be because you're exited about getting market rents with no voids for the next 3 years. \n");
      out.write("              If you are still not sure that you want a passive income with hassle then please see the videos on the about us page.\n");
      out.write("               But remember you worked hard enough to buy and refurbish the property, so don't you think you deserve a 3 year rest,\n");
      out.write("                I do so don't delay register now.</p>\n");
      out.write("            </article>\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("            <a href=\"#regLandlord\" id=\"regLandlord\">Register</a> </div>\n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"box-for\">\n");
      out.write("          <div class=\"img-bx nex1\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/contracter.jpg\" width=\"595\" height=\"347\" />\n");
      out.write("            <div class=\"cut-im nex2\"></div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"cont-box nex\">\n");
      out.write("            <h1 class=\"heading1\">Contractor</h1>\n");
      out.write("            <article>\n");
      out.write("              <p>\n");
      out.write("              Ok, so as a contractor, you want to get paid for services delivered , well you have come to the right place, \n");
      out.write("              once you have registered and provided all of the required information you will part of an exclusive group of contractors\n");
      out.write("               that will be servicing Ashantidutch Property Letting Ltd and a national charity property portfolio.<br /><br />\n");
      out.write("              \n");
      out.write("              Once registered we will agree your rates in principal  and establish call out charges payable to you if needed, thus ensuring you get paid when you need it as without your help will not succeed.\n");
      out.write("              \n");
      out.write("              </p>\n");
      out.write("            </article>\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("            <a href=\"#regContractor\" id=\"regContractor\">Register</a> </div>\n");
      out.write("          <div class=\"clearfix\"></div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write(" </div>");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write(" ");
      out.write("<footer>\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"span12\"> <span>Copyright ©2014 The Novoids Man Ltd. | All Rights Reserved | <a href=\"http://www.thenovoidsman.com/privacy-policy/\">Privacy Policy</a> | <a href=\"http://www.thenovoidsman.com/acceptable-use-policy/\">Acceptable Policy</a></span>\n");
      out.write("        <div class=\"socal\"> \n");
      out.write("                <a href=\"https://www.facebook.com/Ashantidutchpropertylettinglimited\" class=\"fb\" target=\"_blank\"></a> \n");
      out.write("                <a href=\"https://twitter.com/Ashantidutch\" class=\"tw\" target=\"_blank\"></a> \n");
      out.write("                <a href=\"https://www.linkedin.com/pub/neville-douglas/20/120/856\" class=\"in\" target=\"_blank\"></a> \n");
      out.write("                <a href=\" https://plus.google.com/u/0/117314760088509328656/posts\" class=\"gp\" target=\"_blank\"></a> \n");
      out.write("                <a href=\"https://www.youtube.com/user/TheAshantidutch/featured?view_as=public\" class=\"yp\" target=\"_blank\"></a> \n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("<div class=\"lightbox\" id=\"fl1\">\r\n");
      out.write("  <h2 class=\"heading2\">Login</h2>\r\n");
      out.write("  <form action=\"j_spring_security_check\" method=\"post\" >\r\n");
      out.write("    <label>User Name</label>\r\n");
      out.write("    <input type=\"text\" value=\"\" placeholder=\"UserName\" class=\"\" name=\"j_username\"  />\r\n");
      out.write("    <!--<ul class=\"error\">\r\n");
      out.write("    \t<li>Error</li>\r\n");
      out.write("    </ul>-->\r\n");
      out.write("    <label>Password</label>\r\n");
      out.write("    <input type=\"password\" value=\"\" placeholder=\"Enter Your Password\" class=\"\" name=\"j_password\" />\r\n");
      out.write("    <input type=\"submit\" value=\"Log In\" />\r\n");
      out.write("  </form>\r\n");
      out.write("  <a href=\"#\">Forgot Password ?</a> <a href=\"#\">Creat Account</a>\r\n");
      out.write(" </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/index.jsp(123,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t");
        out.write("\r\n");
        out.write("\t\t\t<div id=\"alertErrorId\" class=\"alert alert-block alert-error fade in\" >\r\n");
        out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\r\n");
        out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"errorId\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h4>\r\n");
        out.write("        </div>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/jsp/index.jsp(130,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msg}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t");
        out.write("\r\n");
        out.write("\t\t\t<div id=\"alertSuccessId\" class=\"alert alert-block alert-success fade in\" >\r\n");
        out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\r\n");
        out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"successMessageId\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("</h4>\r\n");
        out.write("        </div>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
