/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-07 07:24:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.profile;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/profile/settings.js\"></script> \r\n");
      out.write(" <div class=\"container-ar\">\r\n");
      out.write("  <section class=\"contant-area\">\r\n");
      out.write("  \t<div id=\"errorId\" class=\"alert alert-block alert-error fade in\" hidden=\"true\" >\r\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\r\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"errorId\">You got an error!</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"alertSuccessId\" class=\"alert alert-block alert-success fade in\" style=\"display: none;\" >\r\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\r\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"successMessageId\"></h4>\r\n");
      out.write("        </div>\r\n");
      out.write("    <div class=\"button\">\r\n");
      out.write("    \t<button id=\"updateAdmin\">Edit</button>\r\n");
      out.write("    \t<button id=\"updateCredentials\">Update Credentials</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"rgpinnew\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li><strong>Firstname</strong><samp>:</samp><span id=\"firstName\"></span></li>\r\n");
      out.write("            <li><strong>Lastname</strong><samp>:</samp><span id=\"lastName\"></span></li>\r\n");
      out.write("            <li><strong>Reference</strong><samp>:</samp><span id=\"reference\"></span></li>\r\n");
      out.write("            <li><strong>Username</strong><samp>:</samp><span id=\"username\"></span></li>\r\n");
      out.write("            <li id=\"citiesallotedliId\"><strong>Cities Alloted</strong><samp>:</samp><span id=\"cities\"></span></li>   \r\n");
      out.write("            <li><strong>Password</strong><samp>:</samp><span id=\"password\"></span></li>\r\n");
      out.write("            <li><strong>Address Line 1</strong><samp>:</samp><span id=\"addressLine1\"></span></li>\r\n");
      out.write("            <li><strong>Address Line 2</strong><samp>:</samp><span id=\"addressLine2\"></span></li>\r\n");
      out.write("            <li><strong>City</strong><samp>:</samp><span id=\"city\"></span></li>\r\n");
      out.write("            <li><strong>County</strong><samp>:</samp><span id=\"county\"></span></li>\r\n");
      out.write("            <li><strong>Post Code</strong><samp>:</samp><span id=\"postcode\"></span></li>\r\n");
      out.write("            <li><strong>Email Id</strong><samp>:</samp><span id=\"emailId\"></span></li>\r\n");
      out.write("            <li><strong>Phone Number</strong><samp>:</samp><span id=\"phoneNumber\"></span></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("        </div>    \r\n");
      out.write("  </section>\r\n");
      out.write("  <div style=\"display:none;\">\r\n");
      out.write("  <div id='edit'>\r\n");
      out.write("    <form id=\"editPopupFormId\" action=\"javascript:editPopupForm()\">\r\n");
      out.write("      <h1>Edit Admin Details</h1>\r\n");
      out.write("      <div class=\"form-element\">\r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">      \r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Firstname:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"firstName\" id=\"first_Name\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Lastname:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"lastName\" id=\"last_Name\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("           <tr id=\"emailIdTr\">\r\n");
      out.write("            <td><label>Email Id :</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.emailId\" id=\"email_Id\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Address Line 1:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" id=\"address_Line1\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Address Line 2:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" id=\"address_Line2\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>City:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" id=\"address_city\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>County:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" id=\"address_county\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Post Code:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" id=\"address_postCode\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Phone Number:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.phoneNumber\" id=\"address_phoneNumber\"/></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"edit_footer\"><input type=\"submit\" value=\"Update\" /></div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-class\" id='updateCredentialsDiv'>\r\n");
      out.write("    <form id=\"fChangePassword\">\r\n");
      out.write("      <h1>Edit Credentials</h1>\r\n");
      out.write("      <div class=\"form-element\">\r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("          <tr id=\"userNameTrId\">\r\n");
      out.write("            <td width=\"25%\"><label>User Name:</label></td>\r\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"username\" id=\"user_name\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Current Password:</label></td>\r\n");
      out.write("            <td><input type=\"password\" value=\"\" class=\"\" name=\"currentPassword\" id=\"currentPassword\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>New Password:</label></td>\r\n");
      out.write("            <td><input type=\"password\" value=\"\" class=\"\" name=\"newPassword\" id=\"newPassword\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td><label>Confirm Password:</label></td>\r\n");
      out.write("            <td><input type=\"password\" value=\"\" class=\"\" name=\"confirmPassword\" id=\"confirmPassword\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"create_footer\"><input type=\"button\" value=\"Update\" id=\"updateCredentialsBtn\" /></div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
