/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-14 14:18:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.pmc.proposedProperty;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class proposedDevelopment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <sections class=\"contant-area\">\r\n");
      out.write("    <div class=\"button\">\r\n");
      out.write("    <button id=\"viewPDButtonId\">View</button>\r\n");
      out.write("      <button id=\"editButtonId\" style=\"display: none;\">Edit</button>\r\n");
      out.write("      <button id=\"createButtonId\" style=\"display: none;\">Create</button>\r\n");
      out.write("      <button id=\"deleteButtonId\" style=\"display: none;\">Delete</button>\r\n");
      out.write("    </div><!-- table  --><!--  -->\r\n");
      out.write("    \r\n");
      out.write("        <table id=\"dataTableId\" class=\"table display table-bordered\"  cellspacing=\"0\">\r\n");
      out.write("    <thead>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <th>S.No.</th>\r\n");
      out.write("            <th>Created On</th>\r\n");
      out.write("            <th>Contact Person</th>\r\n");
      out.write("            <th>City</th>\r\n");
      out.write("            <th>Address</th>\r\n");
      out.write("            <th>Reference</th>\r\n");
      out.write("            <th>Post Code</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("   </table>\r\n");
      out.write("  </sections>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  var table;\r\n");
      out.write("  var globalDataArr = [];\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("\t\t\t$.fn.dataTable.TableTools.defaults.aButtons = [];\r\n");
      out.write("\t\t\t$.fn.dataTableExt.sErrMode = 'console';\r\n");
      out.write("\t\t\t table = $('#dataTableId').DataTable( {\r\n");
      out.write("\t\t\t        dom: 'Tfrtip',\"ajax\": {\r\n");
      out.write("\t\t\t            \"url\": contextPath +\"/pmc/loadAllpdProperties.htm\",\r\n");
      out.write("\t\t\t            \"type\": \"POST\",\r\n");
      out.write("\t\t\t            \"dataType\": \"json\"\r\n");
      out.write("\t\t\t        },tableTools: {\r\n");
      out.write("\t\t\t                \"aButtons \": [\r\n");
      out.write("\t\t\t                          ]\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        columns: [\r\n");
      out.write("\t\t\t            { data: null, orderable: false },\r\n");
      out.write("\t\t\t            { data: \"createdOn\"},\r\n");
      out.write("\t\t\t            { data: \"contactPerson\" },\r\n");
      out.write("\t\t\t            { data: \"addressObj.city\" },\r\n");
      out.write("\t\t\t            { data: \"addressObj.addressLine1\" },\r\n");
      out.write("\t\t\t            { data: \"uniqueReference\" },\r\n");
      out.write("\t\t\t            { data: \"addressObj.postCode\" },\r\n");
      out.write("\t\t\t        ],\r\n");
      out.write("\t\t\t        \"pageLength\": 15,\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t        \"fnRowCallback\": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {\r\n");
      out.write("\r\n");
      out.write("\t\t              \t  $(\"td:first\", nRow).html(iDisplayIndex +1);\r\n");
      out.write("\t\t\t               return nRow;\r\n");
      out.write("\t\t\t\t     }\r\n");
      out.write("\t\t\t    } );\r\n");
      out.write("   \r\n");
      out.write("\t\t\t$('#dataTableId tbody').on( 'click', 'tr', function () {\r\n");
      out.write("\t\t\t    if ($(this).hasClass('selected')) {\r\n");
      out.write("\t\t\t        $(this).removeClass('selected');\r\n");
      out.write("\t\t\t        $.colorbox.remove();\r\n");
      out.write("\t\t\t    }else {\r\n");
      out.write("\t\t\t        table.$('tr.selected').removeClass('selected');\r\n");
      out.write("\t\t\t        $(this).addClass('selected');\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t} );\r\n");
      out.write("  }); \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  $( \"#viewPDButtonId\").click(function() {\r\n");
      out.write("\t\ttry{ \r\n");
      out.write("\t\t\tvar pmcId = table.row('.selected').data().id;\r\n");
      out.write("\t\t}catch (e) {\r\n");
      out.write("\t\t\t$(\"#commonMessageErrorId\").html(\"Please select a row to view\");\r\n");
      out.write("\t\t\t$(\"#commonMessageErrorId\").fadeIn();\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t$(\"#commonMessageErrorId\").fadeOut(4000);\r\n");
      out.write("\t\t\t}, 2000);\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("        $.ajax({\r\n");
      out.write("      \t\turl : contextPath+\"/pmc/viewPropertyDeveloper.htm\",\r\n");
      out.write("      \t\tmethod: \"Post\",\r\n");
      out.write("      \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("      \t\tsuccess:function(response){\r\n");
      out.write("      \t\t\t\t$(\"#containerId\").html(response);\r\n");
      out.write("      \t\t\t\tpdProperty.Add(pmcId);\r\n");
      out.write("      \t\t\t\t\r\n");
      out.write("      \t  },\r\n");
      out.write("      \t  error: function(error){\r\n");
      out.write("  \t\t\t\tconsole.log(error);\r\n");
      out.write("  \t\t\t\talert(error);\r\n");
      out.write("  \t  }});\r\n");
      out.write("      });\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction validateAOP(formId){\r\n");
      out.write("\t\t  $(formId)[0].reset();\r\n");
      out.write("\t\t  var validator = $(formId).validate();\r\n");
      out.write("\t\t  validator.resetForm();\r\n");
      out.write("\t\t  $(\"label.error\").remove();\r\n");
      out.write("\t\t  $(\".error\").removeClass();\r\n");
      out.write("} \r\n");
      out.write("  </script>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
