/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-20 12:43:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.property;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewPropertyAdminUploadedDocuments_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/common/common.jsp", Long.valueOf(1436246875542L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/form2Object.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/json2.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/datatables/css/font-awesome.min.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" target=\"_blank\" media=\"screen\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/datatables/css/popup.css\" />\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/net/jquery.dataTables.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/net/bootstrap.min.css\"/>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/net/dataTables.bootstrap.css\"/>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/datatables/css/tableTools.css\"/>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/datatables/css/admin-style.css\"></link>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/logout-popup-elements.css\"></link> \n");
      out.write("<link rel=\"stylesheet\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/api/chosen/chosen-prism.css\" />\n");
      out.write("<link rel=\"stylesheet\" rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/api/chosen/chosen.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/fancybox/jquery.fancybox.css\" type=\"text/css\" media=\"screen\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- ---------------- JavaScript --------------------------------->\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.js\"></script>\n");
      out.write("<link rel=\"shortcut icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/resource/images/favicon.ico\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/logout-popup.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("(function() {\n");
      out.write("\t  // Union of Chrome, Firefox, IE, Opera, and Safari console methods\n");
      out.write("\t  var methods = [\"assert\", \"assert\", \"cd\", \"clear\", \"count\", \"countReset\",\n");
      out.write("\t    \"debug\", \"dir\", \"dirxml\", \"dirxml\", \"dirxml\", \"error\", \"error\", \"exception\",\n");
      out.write("\t    \"group\", \"group\", \"groupCollapsed\", \"groupCollapsed\", \"groupEnd\", \"info\",\n");
      out.write("\t    \"info\", \"log\", \"log\", \"markTimeline\", \"profile\", \"profileEnd\", \"profileEnd\",\n");
      out.write("\t    \"select\", \"table\", \"table\", \"time\", \"time\", \"timeEnd\", \"timeEnd\", \"timeEnd\",\n");
      out.write("\t    \"timeEnd\", \"timeEnd\", \"timeStamp\", \"timeline\", \"timelineEnd\", \"trace\",\n");
      out.write("\t    \"trace\", \"trace\", \"trace\", \"trace\", \"warn\"];\n");
      out.write("\t  var length = methods.length;\n");
      out.write("\t  var console = (window.console = window.console || {});\n");
      out.write("\t  var method;\n");
      out.write("\t  var noop = function() {};\n");
      out.write("\t  while (length--) {\n");
      out.write("\t    method = methods[length];\n");
      out.write("\t    // define undefined methods as noops to prevent errors\n");
      out.write("\t    if (!console[method])\n");
      out.write("\t      console[method] = noop;\n");
      out.write("\t  }\n");
      out.write("\t})();\n");
      out.write("</script>\n");
      out.write("<script>\n");
      out.write("    var contextPath ;\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\tcontextPath = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t\t\t$(\"#logoutBtnId\").click(function(){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t\t      type: \"get\",\n");
      out.write("\t\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t\t      success: function(response){\n");
      out.write("\t\t\t\t    \t  \n");
      out.write("\t\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t\t    \t }\n");
      out.write("\t\t\t\t      },\n");
      out.write("\t\t\t\t      error:function(){\n");
      out.write("\t\t\t\t    \t  console.log('Some error is there.');\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t  });\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#continueBtnId\").click(function(){\n");
      out.write("\t\t\t\twindow.location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/home.htm\";\n");
      out.write("\t\t\t});\n");
      out.write("\t\tconsole.log(contextPath);\n");
      out.write("\t\t});\n");
      out.write("\tfunction getContextPath() {\n");
      out.write("\t\t   return \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\t\t}\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t  var homemaxage = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${homemaxage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\n");
      out.write("\t  \n");
      out.write("\t var stop = true;\n");
      out.write("  \t var maxage =\"\";\n");
      out.write("  \t var name = \"maxage\" + \"=\";\n");
      out.write("  \t var intval = 1000;\n");
      out.write("  \t \n");
      out.write("  \t setInterval(function (){\n");
      out.write("  \t\t \n");
      out.write("  \t   \t var cdata = document.cookie.split(';');\n");
      out.write("        // console.log(cdata);\n");
      out.write("         \n");
      out.write("  \t   \t  for(var i=0; i<cdata.length; i++){\n");
      out.write("\n");
      out.write("  \t   \t  \tvar c = cdata[i].trim();\n");
      out.write("  \t   \t  \tif (c.indexOf(\"maxage\")==0){\n");
      out.write("  \t   \t  \t\t\tmaxage = c.substring(name.length,c.length);\n");
      out.write("  \t   \t  \t\t\tif(maxage == homemaxage){\n");
      out.write("  \t   \t  \t\t\t\tdocument.cookie ='maxage='+maxage;\n");
      out.write("  \t   \t  \t\t\t\tstop = true;\n");
      out.write("  \t   \t  \t\t\t}\n");
      out.write("  \t   \t  \t    \tbreak;\t\n");
      out.write("  \t   \t \t\t}\n");
      out.write("  \t   \t  }\n");
      out.write("  \t   \t \n");
      out.write("  \t   \t  if(maxage != null && maxage!=\"\"){\n");
      out.write("  \t   \t\t  maxage = parseInt(maxage)-1000;\n");
      out.write("  \t   \t\t  if(parseInt(maxage) <= 0.00){\n");
      out.write("  \t   \t\t\t  document.cookie =name+\";expires=\"+new Date();\n");
      out.write("  \t   \t\t\t$.ajax({\n");
      out.write("    \t\t\t\t  url: contextPath+\"/home/applicationLogout.htm\",\n");
      out.write("    \t\t\t      type: \"GET\",\n");
      out.write("    \t\t\t      dataType : \"json\",\n");
      out.write("    \t\t\t      success: function(response){\n");
      out.write("    \t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("    \t\t\t    \t\twindow.location.href = contextPath+'/j_spring_security_logout';\n");
      out.write("    \t\t\t    \t }\n");
      out.write("    \t\t\t      },\n");
      out.write("    \t\t\t      error:function(){\n");
      out.write("    \t\t\t         console.log('Some error is there.');\n");
      out.write("    \t\t\t      }\n");
      out.write("    \t\t\t  });\n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t\t  \n");
      out.write("  \t   \t\t  }\n");
      out.write("  \t   \t\t  document.cookie ='maxage='+maxage;\n");
      out.write("  \t     \t\t  if(parseInt(maxage) < (2*60*1000)){\n");
      out.write("  \t     \t\t\t  if(stop){\n");
      out.write("  \t     \t\t\t\t var logoutStr = getLogoutTime();\n");
      out.write("  \t     \t\t\t\tconsole.log(logoutStr);\n");
      out.write("  \t     \t\t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t\t\tlogoutPopUp('bodyId', 'logoutWindowId');\n");
      out.write("  \t     \t\t\t\tstop =false;\n");
      out.write("  \t     \t\t\t\t\n");
      out.write("  \t     \t\t\t  }\n");
      out.write("  \t     \t\t\t var logoutStr = getLogoutTime();\n");
      out.write("\t     \t\t\t\tconsole.log(\"appending : \" + logoutStr);\n");
      out.write("\t     \t\t\t$(\"#timeLeftId\").html(logoutStr);\n");
      out.write("  \t     \t\t  }\n");
      out.write("  \t   \t  }\n");
      out.write("  \t    }, intval);\n");
      out.write("  \t \n");
      out.write(" \n");
      out.write("  \tfunction getLogoutTime(){\n");
      out.write("        var ch  =  (((parseInt(maxage)/(60*1000)).toFixed(2)).toString()).split(\".\");   \n");
      out.write("        if(ch[0]>0){\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+((parseInt(maxage)-(ch[0]*60*1000))/1000)+\" sec(s)\";\n");
      out.write("        }else{\n");
      out.write("     \t   return \"\"+ch[0]+\" min(s) \"+(parseInt(maxage)/1000)+\" sec(s)\";   \n");
      out.write("        }\n");
      out.write("    };\n");
      out.write(" }); \n");
      out.write(" \n");
      out.write("$(document).ready (function(){\n");
      out.write("\t$('.effect').click(function(){\n");
      out.write("\t\t$(this).addClass('add-effect');\n");
      out.write("\t});\n");
      out.write("\t$('.effect').blur(function(){\n");
      out.write("\t\t$(this).removeClass('add-effect');\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/form2Object.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/form/json2.js\"></script>\n");
      out.write("<script  src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.colorbox.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/fancybox/jquery.fancybox.pack.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/net/jquery.dataTables.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/net/dataTables.bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/datatables/js/tableTools.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.carouFredSel-5.6.4-packed.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin.js\"></script>\n");
      out.write("<script src=\"http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/logout-popup.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/common.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/progress-bar/progressbar.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/api/chosen/chosen.jquery.js\" type=\"text/javascript\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/api/chosen/chosen.prism.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" >\n");
      out.write("\tvar fade = 2000;\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t\t\t$(\"#logouthrefId\").click(function(){\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t  url: contextPath+\"/home/userLogout.htm\",\n");
      out.write("\t\t\t\t      type: \"get\",\n");
      out.write("\t\t\t\t      dataType : \"json\",\n");
      out.write("\t\t\t\t      success: function(response){\n");
      out.write("\t\t\t\t    \t if(response.success == 'true' || response.success == true){\n");
      out.write("\t\t\t\t    \t\t window.location.href = contextPath+\"/j_spring_security_logout\";\n");
      out.write("\t\t\t\t    \t }\n");
      out.write("\t\t\t\t      },\n");
      out.write("\t\t\t\t      error:function(){\n");
      out.write("\t\t\t\t         console.log('Some error is there.');\n");
      out.write("\t\t\t\t      }\n");
      out.write("\t\t\t\t  });\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t$(\"#uploadPropertyDocumentBtn\").click(function(){\n");
      out.write("\t\t\t\t$( \"#uploadPropertyDocument\" ).submit();\n");
      out.write("\t\t\t}); \n");
      out.write("\t\t\t/*$( \"#BackButtonId\" ).click(function() {\n");
      out.write("\t\t\t\t alert(\"sfssfskk\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t      });*/\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$('#BackButtonId1').click(function() {\n");
      out.write("\t\t\t\t/* url:contextPath+\"/admin/viewPropertyDeveloper.htm?pdId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${property.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\", */\n");
      out.write("\t\t\t\t//alert(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t   \t\turl:contextPath+\"/admin/viewProperty.htm?propertyId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\n");
      out.write("\t\t\t   \t\tmethod: \"Post\",\n");
      out.write("\t\t\t   \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t   \t\tsuccess:function(data){\n");
      out.write("\t\t\t   \t\t\twindow.parent.$(\"#containerId\").html(data);\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t   \t  \terror: function(error){}\n");
      out.write("\t\t\t     });\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t      \n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tfunction removeDocument(docId) {\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\tbeforeSend: function(){\n");
      out.write("\t\t\t\t\t\t$(\".loader\").css('height', $(document).height());\n");
      out.write("\t\t\t\t\t\t$(\".loader\").css('display', 'block');\t\t\t\t    \n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t    url:contextPath+\"/admin/removePropertyDocuments.htm?docId=\" + docId + \"&propertyId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\n");
      out.write("\t\t\t  \t\tmethod: \"Post\",\n");
      out.write("\t\t\t  \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t  \t\tsuccess:function(data){\n");
      out.write("\t\t\t  \t\t\t$(\".loader\").css('display', 'none');\n");
      out.write("\t\t\t  \t\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/viewPropertyAdminUploadedDocuments.htm?propertyId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t  \t  \terror: function(error){}\n");
      out.write("\t\t\t    });\n");
      out.write("\t\t }\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t \n");
      out.write("\t\t \n");
      out.write("\t\t \n");
      out.write("\t</script>\n");
      out.write("\t<div class=\"container-ar\">\n");
      out.write("\t\t<div class=\"rgpinnew newRGPinner\">\n");
      out.write("\t\t\t<ul> \n");
      out.write("            \t<li>\n");
      out.write("            \t\t  <div class=\"button\"><button id=\"BackButtonId1\">Back</button></div>  \n");
      out.write("  \n");
      out.write("      \t\t \t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("      \t\t \t\t\t<tr>\n");
      out.write("      \t\t \t\t\t\t<td>\n");
      out.write("      \t\t \t\t\t\t\t\t<section class=\"AttachFile\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("   \n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/viewPropertyAdminUploadedDocuments.htm?propertyId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" id=\"uploadPropertyDocument\" method=\"post\" enctype=\"multipart/form-data\" >\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t<table class=\"formTable\" width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><label id=\"uploadBankDocumentLbl\">Select File:</label></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id = \"uploadBankDocumentFile\" name = \"attachFiles\" value = \"Select File\" multiple=\"multiple\"/>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"errorfile\">Please Select file</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><textarea class=\"prpsedtxt\" rows=\"20\" cols=\"15\" name=\"propertyDescription\" placeholder=\"Description...\"></textarea></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><input type=\"button\" id = \"uploadPropertyDocumentBtn\" name=\"bankDocumentDiv\"  value = \"Submit\" /></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t \t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t\t</td>\n");
      out.write("      \t\t \t\t\t</tr>\n");
      out.write("      \t\t \t\t</table>\n");
      out.write("            \t</li>\n");
      out.write("            </ul>\n");
      out.write("            <div class=\"clearfix\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write(" \n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(128,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${propertyObj != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("\t               \t\t\t\t\t\t");
        if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("\t               \t\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("                \t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(129,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("adminUploadedDoc");
    // /WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(129,22) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(129,22) '${propertyObj.getDocuments()}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${propertyObj.getDocuments()}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(130,22) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("AdminUploadedDocObj");
    // /WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(130,22) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/admin/property/viewPropertyAdminUploadedDocuments.jsp(130,22) '${adminUploadedDoc}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${adminUploadedDoc}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t               \t\t\t\t\t\t\t<div class=\"AttachDoc\"><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("/download/uploadedDocuments.htm?fileId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AdminUploadedDocObj.getFileId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" target=\"_blank\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AdminUploadedDocObj.getFileName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</a>\n");
          out.write("\t               \t\t\t\t\t\t\t\t<span onclick=\"removeDocument('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AdminUploadedDocObj.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\"></span>\n");
          out.write("\t               \t\t\t\t\t\t\t</div>\n");
          out.write("\t               \t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
