/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-14 14:07:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.pmc.property;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class property_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/progress-bar/progressbar.js\"></script>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <sections class=\"contant-area\">\n");
      out.write("    <div class=\"button\">\n");
      out.write("    <button id=\"viewButtonId\">View</button>\n");
      out.write("      <button id=\"editButtonId\" style=\"display: none;\">Edit</button>\n");
      out.write("      <button id=\"createButtonId\" style=\"display: none;\">Create</button>\n");
      out.write("      <button id=\"deleteButtonId\" style=\"display: none;\">Delete</button>\n");
      out.write("    </div><!-- table  --><!--  -->\n");
      out.write("    \n");
      out.write("        <table id=\"dataTableId\" class=\"table display table-bordered\"  cellspacing=\"0\">\n");
      out.write("    <thead>\n");
      out.write("        <tr>\n");
      out.write("            <th>S.No.</th>\n");
      out.write("            <th>Created On</th>\n");
      out.write("            <th>Contact Person</th>\n");
      out.write("            <th>City</th>\n");
      out.write("            <th>Address</th>\n");
      out.write("            <th>Reference</th>\n");
      out.write("            <th>Post Code</th>\n");
      out.write("            <th width=\"250px\">Status</th>\n");
      out.write("        </tr>\n");
      out.write("    </thead>\n");
      out.write("</table>\n");
      out.write("  </sections>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div style=\"display:none;\">\n");
      out.write("  <div id='edit'>\n");
      out.write("    <form id=\"editPopupForm\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Edit Property Details</h1>\n");
      out.write("      <div class=\"form-element\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"40%\"><label>Contact Person:</label></td>\n");
      out.write("            <td width=\"60%\"><input type=\"text\" value=\"\" class=\"\" name=\"contactPerson\" id=\"contactPerson\"/></td>\n");
      out.write("          </tr>         \n");
      out.write("          <tr>\n");
      out.write("            <td><label>Agent Name:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"agentName\" id=\"agentName\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Agent Contact Number:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"agentContactNumber\" id=\"agentContactNumber\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Agent Address:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"agentAddressLine\" id=\"agentAddressLine\"/></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"edit_footer\"><input type=\"submit\" value=\"Update\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("   <div id='create'>\n");
      out.write("    <form id=\"createPopupFormId\" action=\"javascript:createPopupForm()\">\n");
      out.write("      <h1>Register Property</h1>\n");
      out.write("      <div class=\"form-element1\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"25%\"><label>City:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" /></td>\n");
      out.write("            <td width=\"25%\"><label>PostCode:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>First Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"firstName\" /></td>\n");
      out.write("            <td><label>Last Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"lastName\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"primaryEmailId\" /></td>\n");
      out.write("            <td><label>Secondary Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"secondaryEmailId\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Contact Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"primaryPhoneNumber\" /></td>\n");
      out.write("            <td><label>Secondary Contact Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"secondaryPhoneNumber\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>User Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"loginObj.username\" /></td>\n");
      out.write("            <td><label>Password:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"loginObj.password\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line 1:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" /></td>\n");
      out.write("            <td><label>Address line 2:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"create_footer\"><input type=\"submit\" value=\"Create\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("     <div id='delete'>\n");
      out.write("    <form id=\"deletePopupFormId\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Delete Property</h1>\n");
      out.write("      <div class=\"form-element\">\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div id=\"delete_footer\"><input id=\"delete_yes\" type=\"button\" value=\"Yes\" style=\"background-color:#E33A0C\"/>&nbsp&nbsp<input id=\"delete_no\" type=\"button\" value=\"No\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div> \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("  var table;\n");
      out.write("  var globalDataArr = [];\n");
      out.write("  $(document).ready(function(){\n");
      out.write("\t  \t\n");
      out.write("\t\t\t$.fn.dataTable.TableTools.defaults.aButtons = [];\n");
      out.write("\t\t\t$.fn.dataTableExt.sErrMode = 'console';\n");
      out.write("\t\t\t table = $('#dataTableId').DataTable( {\n");
      out.write("\t\t\t        dom: 'Tfrtip',\"ajax\": {\n");
      out.write("\t\t\t            \"url\": contextPath +\"/pmc/loadAllProperties.htm\",\n");
      out.write("\t\t\t            \"type\": \"POST\",\n");
      out.write("\t\t\t            \"dataType\": \"json\"\n");
      out.write("\t\t\t        },tableTools: {\n");
      out.write("\t\t\t                \"aButtons \": [\n");
      out.write("\t\t\t                          ]\n");
      out.write("\t\t\t        },\n");
      out.write("\t\t\t        columns: [\n");
      out.write("\t\t\t            { data: null, defaultContent: '<input type=\"checkbox\" />', orderable: false },\n");
      out.write("\t\t\t            { data: \"createdOn\"},\n");
      out.write("\t\t\t            { data: \"contactPerson\" },\n");
      out.write("\t\t\t            { data: \"addressObj.city\" },\n");
      out.write("\t\t\t            { data: \"addressObj.addressLine1\" },\n");
      out.write("\t\t\t            { data: \"uniqueReference\" },\n");
      out.write("\t\t\t            { data: \"addressObj.postCode\" },\n");
      out.write("\t\t\t            { data: \"statusPercentage\" },\n");
      out.write("\t\t\t        ],\n");
      out.write("\t\t\t        \"pageLength\": 15,\n");
      out.write("\t\t\t        \n");
      out.write("\t\t\t        \"fnRowCallback\": function( nRow, aData, iDisplayIndex, iDisplayIndexFull ) {\n");
      out.write("\t\t\t        \tglobalDataArr.push(aData);\n");
      out.write("\t\t\t        \tvar propertyId =  aData.id;\n");
      out.write("\t\t\t        \tvar htmlStr = '<div id=\"progressBar'+propertyId+'\" class=\"round-pink1\" ><div></div></div>';\n");
      out.write("\t\t\t\t           $('td:eq(7)', nRow).html(htmlStr);\n");
      out.write("\t\t\t\t          \n");
      out.write("\t\t              \t  $(\"td:first\", nRow).html(iDisplayIndex +1);\n");
      out.write("\t\t\t               return nRow;\n");
      out.write("\t\t\t\t     }\n");
      out.write("\t\t\t       \n");
      out.write("\t\t\t    } );\n");
      out.write("\n");
      out.write("\t\t\t $('#dataTableId').on('page.dt',function(){setTimeout(function(){setProgress(globalDataArr);},100);}).dataTable();\n");
      out.write("\t\t\t $('#dataTableId').on('draw.dt', function () {\tsetTimeout(function() { setProgress(globalDataArr);}, 100); });\n");
      out.write("\t\t\t   \n");
      out.write("\t\t\t$('#dataTableId tbody').on( 'click', 'tr', function () {\n");
      out.write("\t\t\t\tprogressBar(10, $('#progressBar'));\n");
      out.write("\t\t\t    if ($(this).hasClass('selected')) {\n");
      out.write("\t\t\t        $(this).removeClass('selected');\n");
      out.write("\t\t\t        $.colorbox.remove();\n");
      out.write("\t\t\t    }else {\n");
      out.write("\t\t\t        table.$('tr.selected').removeClass('selected');\n");
      out.write("\t\t\t        $(this).addClass('selected');\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t} );\n");
      out.write("\t\t\t$( \"#viewButtonId\" ).click(function() {\n");
      out.write("\t\t\t\tvar aData = table.row('.selected').data();\n");
      out.write("\t\t          if(aData!=null){\n");
      out.write("\t\t          $.ajax({\n");
      out.write("\t\t        \t\turl : contextPath+\"/pmc/redirectPropertyDetails.htm\",\n");
      out.write("\t\t        \t\tdata: aData,\n");
      out.write("\t\t        \t\tmethod: \"Post\",\n");
      out.write("\t\t        \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t        \t\tsuccess:function(data){\n");
      out.write("\t\t        \t\t\t\t$(\"#containerId\").html(data);\n");
      out.write("\t\t        \t\t\t\taddPropertyDetails(aData.id);\n");
      out.write("\t\t        \t  },\n");
      out.write("\t\t        \t  error: function(error){\n");
      out.write("\t        \t\t\t\tconsole.log(error);\n");
      out.write("\t        \t\t\t\talert(error);\n");
      out.write("\t        \t  }});\n");
      out.write("\t\t          }\n");
      out.write("\t\t          else{\n");
      out.write("\t\t        \t  $(\"#commonMessageErrorId\").html(\"Please select a row to view\");\n");
      out.write("\t\t\t\t\t\t$(\"#commonMessageErrorId\").fadeIn();\n");
      out.write("\t\t\t\t\t\tsetTimeout(function(){\n");
      out.write("\t\t\t\t\t\t\t$(\"#commonMessageErrorId\").fadeOut(4000);\n");
      out.write("\t\t\t\t\t\t}, 2000);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t        });\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$( \"#editButtonId\" ).click(function() {\n");
      out.write("\t\t\t\tvar aData = table.row('.selected').data();\n");
      out.write("\t\t\t\tif(aData != null){\n");
      out.write("\t\t\t\t\tvalidateAOP(\"#editPopupForm\");\n");
      out.write("\t\t\t\t$('#contactPerson').val(aData.contactPerson);\n");
      out.write("\t\t\t    $('#agentName').val(aData.agentName);\n");
      out.write("\t\t\t    $('#agentContactNumber').val(aData.agentContactNumber);\n");
      out.write("\t\t\t    $('#agentAddressLine').val(aData.agentAddressLine);\n");
      out.write("\t\t\t    $(\"#editButtonId\").colorbox({width:\"580px\", inline:true, href:\"#edit\"});\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse{\n");
      out.write("\t\t\t\t\t$(\"#commonMessageErrorId\").html(\"Please select a row to edit\");\n");
      out.write("\t\t\t\t\t$(\"#commonMessageErrorId\").fadeIn();\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\n");
      out.write("\t\t\t\t\t\t$(\"#commonMessageErrorId\").fadeOut(4000);\n");
      out.write("\t\t\t\t\t}, 2000);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  $( \"#createButtonId\" ).click(function() {\n");
      out.write("\t\t\t\t  var aData = table.row('.selected').data();\n");
      out.write("\t\t\t\t  validateAOP(\"#createPopupFormId\");\n");
      out.write("\t\t          $(\"#createButtonId\").colorbox({width:\"950px\", inline:true, href:\"#create\"});\n");
      out.write("\t\t        });\n");
      out.write("\t\t\t  \n");
      out.write("\t\t\t    $( \"#deleteButtonId\" ).click(function() {\n");
      out.write("\t\t\t    \tvar aData = table.row('.selected').data();\n");
      out.write("\t\t\t          console.log(aData);\n");
      out.write("\t\t\t          if(aData != null)\n");
      out.write("\t\t\t          $(\"#deleteButtonId\").colorbox({width:\"580px\", inline:true, href:\"#delete\"});\n");
      out.write("\t\t\t          else{\n");
      out.write("\t\t\t\t\t\t\talert(\"Please select a row to delete\");\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t    });\n");
      out.write("\t\t\t  \n");
      out.write("\n");
      out.write("\t\t\t$('#delete_no').click(function(){\n");
      out.write("\t\t\t\t$.colorbox.close();\n");
      out.write("\t\t\t});\n");
      out.write("  });\n");
      out.write("  \n");
      out.write("  function setProgress(globalDataArr){\n");
      out.write("\t  \tif (globalDataArr.length > 0) {\n");
      out.write("\t  \t\t$.each(globalDataArr, function(key, value) {\n");
      out.write("\t        \t  progressBar(value.statusPercentage, $('#progressBar'+value.id));\n");
      out.write("\t          });\n");
      out.write("\t      }\n");
      out.write("\t  \tprogressBar(10, $('#progressBar'));\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  function editPopupForm(){\n");
      out.write("\tvar aData = table.row('.selected').data();\n");
      out.write("  \tvar formData = form2object('editPopupForm', '.', true, function(node){\n");
      out.write("  \t\t\t\tif (node.id && node.id.match(/callbackTest/)){\n");
      out.write("  \t\t\t\t\treturn { name: node.id, value: node.innerHTML };\n");
      out.write("  \t\t\t\t}\n");
      out.write("  \t\t\t});\n");
      out.write("  \tformData.id = aData.id;\n");
      out.write("  \tvar jObj = JSON.stringify(formData, null, '\\t');\n");
      out.write("  \t$.ajax({\n");
      out.write("  \t\turl: contextPath+\"/pmc/updateProperty.htm\",\n");
      out.write("  \t\tdata: jObj,\n");
      out.write("  \t\tmethod: \"Post\",\n");
      out.write("  \t\tdataType: \"json\",\n");
      out.write("  \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("  \t\tsuccess:function(result){\n");
      out.write("  \t\t\tif(result.success==true){\n");
      out.write("  \t\t\t\t$.colorbox.close();\n");
      out.write("  \t\t\t\ttable.ajax.reload();\n");
      out.write("  \t\t\t}\n");
      out.write("  \t  }});\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  function createPopupForm(){\n");
      out.write("   var formData = form2object('createPopupFormId', '.', true, function(node){\n");
      out.write("  \t\t\t\tif (node.id && node.id.match(/callbackTest/)){\n");
      out.write("  \t\t\t\t\treturn { name: node.id, value: node.innerHTML };\n");
      out.write("  \t\t\t\t}\n");
      out.write("  \t\t\t});\n");
      out.write("  \tvar jObj = JSON.stringify(formData, null, '\\t');\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("  \tconsole.log(jObj);\n");
      out.write("  \t$.ajax({\n");
      out.write("  \t\t\n");
      out.write("  \t\turl:\"pmc.htm?action=1&param=LANDLORD\",\n");
      out.write("  \t\tdata: jObj,\n");
      out.write("  \t\tmethod: \"Post\",\n");
      out.write("  \t\tdataType: \"json\",\n");
      out.write("  \t\tcontentType: \"application/json\",\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("  \t\tsuccess:function(result){\n");
      out.write("  \t\t\tif(result.success==true){\n");
      out.write("  \t\t\t\t$.colorbox.close();\n");
      out.write("  \t\t\t\ttable.ajax.reload();\n");
      out.write("  \t\t\t}\n");
      out.write("  \t  }});\n");
      out.write("  }  \n");
      out.write("\t\n");
      out.write("  $(function() {\n");
      out.write("\t    $(\"#editPopupForm\").validate({\n");
      out.write("\t        rules: {\n");
      out.write("\t        \t\"contactPerson\": \"required\",\n");
      out.write("\t        \t\"agentName\": \"required\",\n");
      out.write("\t        \t\"agentContactNumber\" : {\n");
      out.write("\t                required: true,\n");
      out.write("\t                digits: true,\n");
      out.write("\t                minlength :10\n");
      out.write("\t            },\n");
      out.write("\t        \t\"agentAddressLine\"  : \"required\",\n");
      out.write("\t        }\n");
      out.write("\t    });\n");
      out.write("\t  });\n");
      out.write("\n");
      out.write("\t$(function() {\n");
      out.write("\t    $(\"#createPopupFormId\").validate({\n");
      out.write("\t        rules: {\n");
      out.write("\t        \t\"firstName\": \"required\",\n");
      out.write("\t        \t\"lastName\": \"required\",\n");
      out.write("\t        \t\"primaryEmailId\": {\n");
      out.write("\t                required: true,\n");
      out.write("\t                email: true\n");
      out.write("\t            },\n");
      out.write("\t        \t\"secondaryEmailId\": {\n");
      out.write("\t                required: true,\n");
      out.write("\t                email: true\n");
      out.write("\t            },\n");
      out.write("\t        \t\"primaryPhoneNumber\" : {\n");
      out.write("\t                required: true,\n");
      out.write("\t                digits: true,\n");
      out.write("\t                minlength :10\n");
      out.write("\t            },\n");
      out.write("\t        \t\"secondaryPhoneNumber\": {\n");
      out.write("\t                required: true,\n");
      out.write("\t                digits: true,\n");
      out.write("\t                minlength :10\n");
      out.write("\t            },\n");
      out.write("\t        \t\"loginObj.username\": \"required\",\n");
      out.write("\t        \t\"loginObj.password\": \"required\",\n");
      out.write("\t        \t\"addressObj.addressLine1\" : \"required\",\n");
      out.write("\t        \t\"addressObj.addressLine2\" : \"required\",\n");
      out.write("\t        \t\"addressObj.postCode\" : \"required\",\n");
      out.write("\t        \t\"addressObj.city\" : \"required\"\n");
      out.write("\t        }\n");
      out.write("\t    });\n");
      out.write("\t  });\n");
      out.write("\t\n");
      out.write("\tfunction validateAOP(formId){\n");
      out.write("\t\t  $(formId)[0].reset();\n");
      out.write("\t\t  var validator = $(formId).validate();\n");
      out.write("\t\t  validator.resetForm();\n");
      out.write("\t\t  $(\"label.error\").remove();\n");
      out.write("\t\t  $(\".error\").removeClass();\n");
      out.write("} \n");
      out.write("  </script>\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
