/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-15 11:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.user.propertyDeveloper.pdProperty;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class savePDPropertyDetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/property.js\"></script>\n");
      out.write("\t <script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/propertyDeveloper.js\"></script> \n");
      out.write("\t\n");
      out.write("  <style>\n");
      out.write("  label.error{\n");
      out.write("\t\tcolor: #FF0000;\n");
      out.write("\t\tfloat: right;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</style> \n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("\t  $(document).ready(function(){\n");
      out.write("\t  \t $.getJSON(contextPath+\"/register/loadLandlordCities.htm\", function(options) {\n");
      out.write("\t   \t      var dropdown = $('#cityDropdown');\n");
      out.write("\t   \t      if (options) {\n");
      out.write("\t   \t    \t  var opts = options.data;\n");
      out.write("\t   \t    \t      dropdown.append($('<option/>').val('').text('Select City'));\n");
      out.write("\t   \t          $.each(opts, function(id, city) {\n");
      out.write("\t   \t        \t  dropdown.append($('<option/>').val(this.id).text(this.city));\n");
      out.write("\t   \t          });\n");
      out.write("\t   \t      \t\t \n");
      out.write("\t   \t      }\n");
      out.write("\t   \t });\n");
      out.write("\t  });\n");
      out.write("\t  \n");
      out.write("\t  new JsDatePick({\n");
      out.write("\t\t\tuseMode:2,\n");
      out.write("\t\t\ttarget:\"estimatedStartDateID\",\n");
      out.write("\t\t\tdateFormat:\"%d-%M-%Y\",\n");
      out.write("\t\t\tlimitToToday:true,\n");
      out.write("\t\t });\n");
      out.write("\t  \n");
      out.write("\t  $(function() {\n");
      out.write("\t\t    $(\"#fPDPropertyDetails\").validate({\n");
      out.write("\t\t        rules: {\n");
      out.write("\t\t        \t\"contactPerson\": \"required\",\n");
      out.write("\t\t        \t\"addressObj.addressLine1\" : \"required\",\n");
      out.write("\t\t        \t\"addressObj.city\" : \"required\",\n");
      out.write("\t\t        \t\"addressObj.county\" : \"required\",\n");
      out.write("\t\t        \t\"addressObj.postCode\" : \"required\",\n");
      out.write("    \t        \t/* \"addressObj.city\": {\n");
      out.write("    \t                required: {\n");
      out.write("    \t                    depends: function(element) {\n");
      out.write("    \t                       if(element.value == 0){\n");
      out.write("    \t                    \t   $(\"#cityErrorId\").show();\n");
      out.write("    \t                    \t   return false;\n");
      out.write("    \t                       }\n");
      out.write("    \t                    \t\n");
      out.write("    \t                    }\n");
      out.write("    \t                }\n");
      out.write("    \t            } */\n");
      out.write("    \t        \t\n");
      out.write("\t\t        },\n");
      out.write("\t\t    messages: {\n");
      out.write("\t\t    \t\"addressObj.city\": { \n");
      out.write("\t\t         required: \"Please Select City.\",\n");
      out.write("\t\t        },\n");
      out.write("\t\t       }\n");
      out.write("\t\t    });\n");
      out.write("\t\t  });\n");
      out.write("\t  \n");
      out.write("\t</script>\n");
      out.write("\n");
      out.write("    <div class=\"row\">\n");
      out.write("      <div class=\"span10\">\n");
      out.write("      \n");
      out.write("        <form name=\"fPDPropertyDetails\" id=\"fPDPropertyDetails\">\n");
      out.write("          <h1 class=\"heading4 margin-top15\">Property Details</h1>\n");
      out.write("          <div >\n");
      out.write("        <div class=\"PropertyForm new-form-stra\">\n");
      out.write("            <span>    <label>Contact Person</label>\n");
      out.write("                <input type=\"hidden\" id=\"propId\">\n");
      out.write("                  <input type=\"text\" placeholder=\"Contact Person\"  class=\"\" name=\"contactPerson\" id=\"contactPerson\" /></span>\n");
      out.write("              <span>  <label>Address Line 1</label>\n");
      out.write("                  <input type=\"text\" placeholder=\"Enter your address\" class=\"\" name=\"addressObj.addressLine1\" id=\"addressLine1\" /></span>\n");
      out.write("             \n");
      out.write("              <span>  <label>Address Line 2</label>\n");
      out.write("                  <input type=\"text\" placeholder=\"Enter your address\" class=\"\" name=\"addressObj.addressLine2\" id=\"addressLine2\" /></span>\n");
      out.write("                \n");
      out.write("            <span>    <label>City</label>\n");
      out.write("                <input type=\"text\" value=\"\" placeholder=\"Enter your city\" class=\"required\" readonly=\"readonly\" name=\"addressObj.city\" id=\"cityId\" style=\"display: none; background-color: #E0E0E0\" />\n");
      out.write("                  <select name=\"addressObj.city\" id=\"cityDropdown\" >\n");
      out.write("\t              </select></span>\n");
      out.write("\t          \n");
      out.write("              <span>  <label>County</label>\n");
      out.write("                  <input type=\"text\" placeholder=\"Enter your County\" class=\"\" name=\"addressObj.county\" id=\"county\" />\n");
      out.write("              </span>\n");
      out.write("                  \n");
      out.write("            <span>    <label>Post Code</label>\n");
      out.write("                  <input type=\"text\" placeholder=\"Enter your zip code\" class=\"\" name=\"addressObj.postCode\" id=\"postCode\" style=\"text-transform: uppercase;\" /></span>\n");
      out.write("             \n");
      out.write("             \n");
      out.write("           <span>  <label> Type Of Proposed Development </label>\n");
      out.write("              <input type=\"text\" name=\"typeOfProposedProp\" placeholder=\"Property Type\" value=\"\" id=\"typeOfProposedPropID\">\n");
      out.write("            </span>\n");
      out.write("            \n");
      out.write("           <span><label>Number Of Units </label>\n");
      out.write("              <input type=\"text\" name=\"noOfUnits\" placeholder=\"Number of Units\" value=\"\" id=\"noOfUnitsID\">\n");
      out.write("           </span>\n");
      out.write("           \n");
      out.write("            <span>\n");
      out.write("            <label>Energy saving features</label>\n");
      out.write("              <input type=\"text\" name=\"energySavingFeatures\" placeholder=\"\tEnergy Saving Features\" id=\"energySavingFeaturesID\">\n");
      out.write("            </span>\n");
      out.write("            \n");
      out.write("             <span class=\"calenter-pick\"><label>Estimated started date  </label>\n");
      out.write("              <input type=\"text\" name=\"estimatedStartDate\" placeholder=\"Estimated Start Date\" id=\"estimatedStartDateID\" readonly=\"readonly\">\n");
      out.write("             </span>\n");
      out.write("           \n");
      out.write("             <span><label>Time to complete scheme</label>\n");
      out.write("              <input type=\"text\" name=\"timeToCompleteSceme\" placeholder=\"Time To Complete Sceme\" id=\"timeToCompleteScemeID\">\n");
      out.write("             </span>\n");
      out.write("             \n");
      out.write("             <span><label>Description  </label>\n");
      out.write("              <textarea name=\"description\" placeholder=\"Additianal Description\" id=\"descriptionID\"></textarea>\n");
      out.write("             </span>\n");
      out.write("             \n");
      out.write("          </div>\n");
      out.write("          </div>\n");
      out.write("          <a href=\"redirectCompleteProperties.htm\" class=\"backbtnnew\">Back</a>\n");
      out.write("           <input type=\"button\" id=\"UpdatePDProperty\" class=\"regis-co\" value=\"Update and Continue\" style=\"display:none;\">\n");
      out.write("          <input type=\"button\" id=\"savePDPropertyDetails\" class=\"regis-co\" value=\"Submit and Continue\">\n");
      out.write("        </form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
