/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-07 07:23:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.sub_002dadmin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class users_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css\">\n");
      out.write("    <script  src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.colorbox.js\"></script>\n");
      out.write("    <script  src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/user/user-support.js\"></script>\n");
      out.write("    <script  src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/user/user-validation.js\"></script>\n");
      out.write("    \n");
      out.write("    <style>\n");
      out.write("    \t.SlectBox, .SlectBoxa {\n");
      out.write(" \t\t   padding: 5px;\n");
      out.write("    \t   width: 470px!important;\n");
      out.write("\t\t}\n");
      out.write("\t\t.SumoSelect > .CaptionCont > label {\n");
      out.write("\t\tright: -13px!important;\n");
      out.write("\t\t}\n");
      out.write("    </style>\n");
      out.write("    \n");
      out.write("<div class=\"container\">\n");
      out.write("  <sections class=\"contant-area\">\n");
      out.write("          <div class=\"button\">\n");
      out.write("      <button id=\"createButtonIdAdmin\">Create</button>\n");
      out.write("      <button id=\"viewButtonIdAdmin\">View</button>\n");
      out.write("      <button id=\"editButtonIdAdmin\">Edit</button>\n");
      out.write("    </div>\n");
      out.write("    <div id=\"alertErrorId\" class=\"alert alert-block alert-error fade in\" style=\"display: none;\">\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"errorId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"alertSuccessId\" class=\"alert alert-block alert-success fade in\"  style=\"display: none;\" >\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"successMessageId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("\t<table id=\"dataTableId1\" class=\"table display table-bordered\"\n");
      out.write("\t\tcellspacing=\"0\">\n");
      out.write("\t\t<thead>\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t\t<th>S.No.</th>\n");
      out.write("\t\t\t\t<th>Created On</th>\n");
      out.write("\t\t\t\t<th>Name</th>\n");
      out.write("\t\t\t\t<th>Reference</th>\n");
      out.write("\t\t\t\t<th>Status</th>\n");
      out.write("\t\t\t\t<th>UserName</th>\n");
      out.write("\t\t\t</tr>\n");
      out.write("\t\t</thead>\n");
      out.write("\t</table>\n");
      out.write("\t<div class=\"clearfix\"></div>\n");
      out.write("  </sections>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div style=\"display:none; height: 100px; weight: 100px\">\n");
      out.write("\n");
      out.write("  \n");
      out.write("   <div id='createAdmin'>\n");
      out.write("    <form id=\"createPopupFormIdAdmin\" >\n");
      out.write("      <h1>Create Admin</h1>\n");
      out.write("      <div id=\"createErrorId\" class=\"alert alert-block alert-error fade in\" hidden=\"true\" >\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"createErrorMessageId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("      <div class=\"form-element1\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"25%\"><label>First Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"firstName\" /></td>\n");
      out.write("            <td width=\"25%\"><label>Last Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"lastName\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>User Name:</label>\n");
      out.write("            \t<input type=\"text\" value=\"\" class=\"\" name=\"loginObj.username\" id=\"userName\" />\n");
      out.write("            \t<label id=\"lbl\" style=\"float: right; color:red;\"></label></td>\n");
      out.write("           \n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("          <td><label>Address Line 1:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" /></td>\n");
      out.write("            <td><label>Address Line 2:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("          <td><label>City:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" /></td>\n");
      out.write("            <td><label>Post Code:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" style=\"text-transform: uppercase;\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("          <td><label>County:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" /></td>\n");
      out.write("            <td><label>Landmark:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.landmark\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.emailId\" /></td>\n");
      out.write("            <td><label>Phone Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.phoneNumber\" /></td>\n");
      out.write("          </tr>             \n");
      out.write("                  \n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"delete_footer\"><input type=\"button\" id=\"createAdminButton\" style=\"background-color:#E33A0C\" value=\"Create\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("      <div id='editAdmin'>\n");
      out.write("    <form id=\"editPopupFormIdAdmin\" >\n");
      out.write("      <h1>Edit Admin</h1>\n");
      out.write("      <div class=\"form-element1\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"25%\"><label>First Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"firstName\" id=\"firstName\"/></td>\n");
      out.write("            <td width=\"25%\"><label>Last Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"lastName\" id=\"lastName\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line 1:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" id=\"addressLine1\"/></td>\n");
      out.write("            <td><label>Address Line 2:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" id=\"addressLine2\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>City:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" id=\"city_\"/></td>\n");
      out.write("             <td><label>Post Code:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" id=\"postCode\" style=\"text-transform: uppercase;\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>County:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" id=\"county\"/></td>\n");
      out.write("            <td><label>LandMark</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.landmark\" id=\"landmark\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.emailId\" id=\"emailId\" style=\"background-color: #E0E0E0\" readonly=\"readonly\"/></td>\n");
      out.write("            <td><label>Phone Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.phoneNumber\" id=\"phoneNumber\"/></td>\n");
      out.write("          </tr>            \n");
      out.write("                  \n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"delete_footer\"><input type=\"button\" id=\"updateAdminButton\" style=\"background-color:#E33A0C\" value=\"Update\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("    <div id='deleteAdmin'>\n");
      out.write("    <form id=\"deletePopupFormId\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Disable Admin</h1>\n");
      out.write("      <div class=\"form-element\">\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("      <div id=\"delete_footer\"><input id=\"delete_yesAdmin\" type=\"button\" value=\"Yes\" style=\"background-color:#E33A0C\"/>&nbsp&nbsp<input id=\"delete_noAdmin\" type=\"button\" value=\"No\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
