/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-07 07:23:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.landlord;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class landlord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resource/css/sumoselect.css\" rel=\"stylesheet\" />\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.sumoselect.min.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/landlord/landlord.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/landlord/landlord-validation.js\"></script>\n");
      out.write("<style>\n");
      out.write(".regis { width:96.8%; padding:8px 2px; border:2px solid #E7E1E1; border-radius:3px; margin-bottom:5px; color:#333; height:38px;background-color:#fff}</style>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <sections class=\"contant-area\">\n");
      out.write("    <div class=\"button\">\n");
      out.write("    <button id=\"viewButtonId\">View</button>\n");
      out.write("      <button id=\"editButtonId\">Edit</button>\n");
      out.write("      <button id=\"createButtonId\" style=\"display:none;\">Create</button>\n");
      out.write("      <button id=\"deleteButtonId\" style=\"display: none;\">Delete</button>\n");
      out.write("    </div><!-- table  --><!--  -->\n");
      out.write("    \n");
      out.write("   <table id=\"dataTableId\" class=\"table display table-bordered\"  cellspacing=\"0\">\n");
      out.write("    <thead>\n");
      out.write("        <tr>\n");
      out.write("            <th>S.No.</th>\n");
      out.write("            <th>Created On</th>\n");
      out.write("            <th>Name</th>\n");
      out.write("            <th>Contact Number</th>\n");
      out.write("             <th width=\"10%\">Property Registered</th>\n");
      out.write("            <th>Reference</th>\n");
      out.write("            <th width=\"18%\">Address</th>\n");
      out.write("            <th>Primary Email Id</th>\n");
      out.write("        </tr>\n");
      out.write("    </thead>\n");
      out.write("</table>\n");
      out.write("  </sections>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div style=\"display:none;\">\n");
      out.write("  <div id='edit'>\n");
      out.write("    <form id=\"editPopupForm\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Edit Landlord Details</h1>\n");
      out.write("      <div class=\"form-element\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"40%\"><label>First Name:</label></td>\n");
      out.write("            <td width=\"60%\"><input type=\"text\" value=\"\" class=\"\" name=\"firstName\" id=\"first_name\"/></td>\n");
      out.write("          </tr>         \n");
      out.write("          <tr>\n");
      out.write("            <td><label>Last Name:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"lastName\" id=\"last_name\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line1:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" id=\"address_line1\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line2:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" id=\"address_line2\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          \n");
      out.write("          <tr>\n");
      out.write("            <td><label>City:</label></td>\n");
      out.write("            <td><select class=\"regis\" name=\"addressObj.city\" id=\"landlordCity\"></select></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Post Code:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" id=\"post_code\" style=\"text-transform: uppercase;\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>County:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" id=\"county\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Email Id:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"primaryEmailId\" id=\"email_id\" style=\"background-color: #E0E0E0\" readonly=\"readonly\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Contact Number:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"primaryPhoneNumber\" id=\"phone_number\"/></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"edit_footer\"><input type=\"submit\" value=\"Update\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("   <div id='create'>\n");
      out.write("    <form id=\"createPopupFormId\" action=\"javascript:createPopupForm()\">\n");
      out.write("      <h1>Register LandLord</h1>\n");
      out.write("      <div class=\"form-element1\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"25%\"><label>City:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" /></td>\n");
      out.write("            <td width=\"25%\"><label>PostCode:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>First Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"firstName\" /></td>\n");
      out.write("            <td><label>Last Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"lastName\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"primaryEmailId\" /></td>\n");
      out.write("            <td><label>Secondary Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"secondaryEmailId\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Primary Contact Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"primaryPhoneNumber\" /></td>\n");
      out.write("            <td><label>Secondary Contact Number:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"secondaryPhoneNumber\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>User Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"loginObj.username\" /></td>\n");
      out.write("            <td><label>Password:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"loginObj.password\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line 1:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" /></td>\n");
      out.write("            <td><label>Address line 2:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" /></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"create_footer\"><input type=\"submit\" value=\"Create\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("     <div id='delete'>\n");
      out.write("    <form id=\"deletePopupFormId\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Delete Landlord</h1>\n");
      out.write("      <div class=\"form-element\">\n");
      out.write("      </div>\n");
      out.write("      <div id=\"delete_footer\"><input id=\"delete_yes\" type=\"button\" value=\"Yes\" style=\"background-color:#E33A0C\"/>&nbsp&nbsp<input id=\"delete_no\" type=\"button\" value=\"No\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>   \n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
