/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-15 05:23:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.settings;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newAttachmentFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/settings/attachmentFile.js\"></script> \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".doc_download{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write(" \t.heading{\r\n");
      out.write("\t\ttext-transform: uppercase;\r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\tfont-size: 20px!important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write(" <div class=\"container-ar\">\r\n");
      out.write("  <section class=\"contant-area\">\r\n");
      out.write("    <div class=\"rgpinnew\">\r\n");
      out.write("          <ul>\r\n");
      out.write("          <li><strong class=\"heading\">Landlord Documents</strong></li>\r\n");
      out.write("            <li><strong>ADPL 1:</strong><samp>:</samp><span id=\"adpl1Id\"></span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"adpl1UploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"adpl1DownloadBtn\" name=\"edit\" url = \"\" value=\"Download\" class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"adpl1Div\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=1\" id=\"uploadADPL1\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadADPL1File\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadADPL1Lbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" id = \"uploadADPL1Btn\" class=\"uploadFiles\" name=\"adpl1Div\"  value =\"Submit\" >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><strong>ADPL 3:</strong><samp>:</samp><span id=\"adpl3Id\"></span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"adpl3UploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"adpl3DownloadBtn\" name=\"edit\" value=\"Download\" url = \"\"  class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"adpl3Div\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=2\" id=\"uploadADPL3\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadADPL3File\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadADPL3Lbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" class=\"uploadFiles\" id = \"uploadADPL3Btn\" name=\"adpl3Div\"  value = \"Submit\" >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><strong>Bank Document:</strong><samp>:</samp><span id=\"bankDocumentId\"> </span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"bankDocumentUploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"bankDocumentDownloadBtn\" name=\"edit\" value=\"Download\" url = \"\"  class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"bankDocumentDiv\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=3\" id=\"uploadBankDocument\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadBankDocumentFile\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadBankDocumentLbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" id = \"uploadBankDocumentBtn\" class=\"uploadFiles\" name=\"bankDocumentDiv\"  value = \"Submit\" >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("                      \r\n");
      out.write("            <li><strong>Terms and Conditions Document: </strong><samp>:</samp><span id=\"termsAndConditionId\"></span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"termsAndConditionUploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"termsAndConditionDownloadBtn\" name=\"edit\" value=\"Download\" url = \"\"  class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"termsAndConditionDiv\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=4\" id=\"uploadTermsAndConditions\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadTermsAndConditionsFile\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadTermsAndConditionsLbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" id = \"uploadTermsAndConditionsBtn\" class=\"uploadFiles\" name =\"termsAndConditionDiv\" value = \"Submit\"  >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><strong class=\"heading\">Property Developer Documents</strong></li>\r\n");
      out.write("            <li><strong>Document 1:</strong><samp>:</samp><span id=\"pdDoc1Id\"></span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"pdDoc1UploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"pdDoc1DownloadBtn\" name=\"edit\" url = \"\" value=\"Download\" class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"pdDoc1Div\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=5\" id=\"uploadPDDoc1\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadPDDocFile1\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadPDDoc1Lbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" id = \"uploadDocBtn1\" class=\"uploadFiles\" name=\"adpl1Div\"  value =\"Submit\" >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("            <li><strong>Document 2:</strong><samp>:</samp><span id=\"pdDoc2Id\"></span>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"pdDoc2UploadBtn\" name=\"edit\" value=\"Upload\" class=\"doc_upload\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("           \t\t <h4><input type=\"button\" id=\"pdDoc2DownloadBtn\" name=\"edit\" url = \"\" value=\"Download\" class=\"doc_download\" style=\"height: 20px;\" /></h4>\r\n");
      out.write("            \t<div id=\"pdDoc2Div\" class=\"edit-prof\" style=\"display:none;\">\r\n");
      out.write("            \t\r\n");
      out.write("            \t<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/admin/uploadFiles.htm?adminDocumentId=6\" id=\"uploadPDDoc2\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"file\" id = \"uploadPDDocFile2\" name = \"uploadedFile\" value = \"Select File\"/> <br>\r\n");
      out.write("\t\t\t\t\t\t   <label id=\"uploadPDDoc2Lbl\" style=\"color: red; width: 25%; margin-bottom: 12px; display: none; \"></label>\r\n");
      out.write("\t\t\t\t\t\t  <input type=\"button\" id = \"uploadDocBtn2\" class=\"uploadFiles\" name=\"\"  value =\"Submit\" >\r\n");
      out.write("\t\t\t\t </form>\r\n");
      out.write("            \t</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"clearfix\"></div>\r\n");
      out.write("        </div>    \r\n");
      out.write("  </section>\r\n");
      out.write("  </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
