/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-07 07:24:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.settings;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" <script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/settings/settings.js\"></script> \r\n");
      out.write("<style>\r\n");
      out.write("/* li.paginate_button{\r\n");
      out.write("\twidth: 25px;\r\n");
      out.write("} */\r\n");
      out.write(".paginate_button.previous.disabled{\r\n");
      out.write("\twidth: 80px!important;\r\n");
      out.write("}\r\n");
      out.write(".tableDiv{\r\n");
      out.write("width:54%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table#dataTableId{\r\n");
      out.write("\twidth: 100%!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"width: 35%!important;\">\r\n");
      out.write("  <sections class=\"contant-area\">\r\n");
      out.write("    <div class=\"button\">\r\n");
      out.write("\t    <button id=\"createButtonId\">Create</button>\r\n");
      out.write("\t   <!--   <button id=\"uploadFileButtonId\">Upload new Files</button> -->\r\n");
      out.write("     \t <button id=\"deleteButtonId\" style=\"display: none;\">Remove</button>\r\n");
      out.write("\t    </div><!-- table  --><!--  -->\r\n");
      out.write("    \r\n");
      out.write("        <table id=\"dataTableId\" class=\"table display table-bordered\"  cellspacing=\"0\">\r\n");
      out.write("    <thead style=\"width: 12px!important;\">\r\n");
      out.write("        <tr style=\"width: 50%!important;\">\r\n");
      out.write("            <th style=\"width: 12px!important;\">S.No.</th>\r\n");
      out.write("            <th style=\"width: 85%!important;\">City</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("</table>\r\n");
      out.write("  </sections>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <div style=\"display:none; height: 100px; weight: 100px\">\r\n");
      out.write("  <div id='create'>\r\n");
      out.write("    <form id=\"createPopupFormId\" >\r\n");
      out.write("      <h1>Create New City</h1>\r\n");
      out.write("      <div class=\"form-element1\">\r\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td><label>Name:</label></td>\r\n");
      out.write("                      <td>\r\n");
      out.write("                        <input type=\"text\" class=\"\" id=\"city\" /></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"delete_footer\"><input type=\"button\" id=\"createCityButton\" value=\"Create\" style=\"background-color:#E33A0C\"/></div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <div id='delete'>\r\n");
      out.write("    <form id=\"deletePopupFormId\" action=\"javascript:editPopupForm()\">\r\n");
      out.write("      <h1>Remove City</h1>\r\n");
      out.write("      <div class=\"form-element\">\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"delete_footer\"><input id=\"delete_yes\" type=\"button\" value=\"Yes\" style=\"background-color:#E33A0C\"/>&nbsp&nbsp<input id=\"delete_no\" type=\"button\" value=\"No\" /></div>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <style>\r\n");
      out.write("  a{\r\n");
      out.write("  color:#E33A0C;\r\n");
      out.write("  }\r\n");
      out.write("  a:hover{\r\n");
      out.write("  color:#E33A0C;\r\n");
      out.write("  }\r\n");
      out.write("  .tab-menu{\r\n");
      out.write("  z-index: 0;\r\n");
      out.write("  }\r\n");
      out.write("  </style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
