/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.37
 * Generated at: 2015-07-14 13:15:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin.pmc;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pmc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<script  src=\"");
      out.print(request.getContextPath());
      out.write("/resource/js/jquery.colorbox.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/pmc/pmc.js\"></script>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resource/perpetual/admin/pmc/pmc-validation.js\"></script>\n");
      out.write("   \n");
      out.write("<div class=\"container\">\n");
      out.write("  <sections class=\"contant-area\">\n");
      out.write("    <div class=\"button\">\n");
      out.write("     <button id=\"createButtonId\">Create</button>\n");
      out.write("     <button id=\"editButtonId\">Edit</button>\n");
      out.write("     <button style=\"display: none;\" id=\"deleteButtonId\">Delete</button>\n");
      out.write("     <button id=\"viewButtonId\">View</button>\n");
      out.write("     <button id=\"viewPMCUsersButtonId\">View Users</button>\n");
      out.write("    </div>\n");
      out.write("   \t <div id=\"alertErrorId\" class=\"alert alert-block alert-error fade in\" style=\"display: none;\">\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"errorId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"mainsuccessId\" class=\"alert alert-block alert-success fade in\"  style=\"display: none;\" >\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"mainsuccessMessageId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("        <table id=\"dataTableId\" class=\"table display table-bordered\"  cellspacing=\"0\">\n");
      out.write("    <thead>\n");
      out.write("        <tr>\n");
      out.write("            \t<th>S.No.</th>\n");
      out.write("            \t<th>Created On</th>\n");
      out.write("\t            <th>Company Name</th>\n");
      out.write("\t            <th>Authorised Person</th>\n");
      out.write("\t            <th>Enable</th>\n");
      out.write("\t            <th>Email</th>\n");
      out.write("\t            <th>Phone Number</th>\n");
      out.write("        </tr>\n");
      out.write("    </thead>\n");
      out.write("</table>\n");
      out.write("  </sections>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div style=\"display:none;\">\n");
      out.write("  <div id='edit'>\n");
      out.write("    <form id=\"editPopupForm\">\n");
      out.write("      <h1>Edit Property Management Company Details</h1>\n");
      out.write("     \n");
      out.write("      <div class=\"form-element\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"40%\"><label>Authorised Person:</label></td>\n");
      out.write("            <td width=\"60%\"><input type=\"text\" value=\"\" class=\"\" name=\"authorisedPerson\" id=\"authorisedPerson\"/></td>\n");
      out.write("          </tr>   \n");
      out.write("          <tr>\n");
      out.write("            <td width=\"40%\"><label>Company Name:</label></td>\n");
      out.write("            <td width=\"60%\"><input type=\"text\" value=\"\" class=\"\" name=\"companyName\" id=\"companyName\"/></td>\n");
      out.write("          </tr>      \n");
      out.write("          <tr>\n");
      out.write("            <td><label>Email Id</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.emailId\" id=\"emailId\" readonly=\"readonly\" style=\"background-color: #E0E0E0\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Contact Number:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.phoneNumber\" id=\"phoneNumber\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line1:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" id=\"addressLine1\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line2:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" id=\"addressLine2\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>City:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" id=\"city\"/></td>\n");
      out.write("          </tr>\n");
      out.write("           <tr>\n");
      out.write("            <td><label>Post Code:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" id=\"postCode\" style=\"text-transform: uppercase;\"/></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>County:</label></td>\n");
      out.write("            <td><input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" id=\"county\"/></td>\n");
      out.write("          </tr>\n");
      out.write("         \n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"edit_footer\"><input type=\"button\" id=\"updateBtnId\" value=\"Update\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write(" \n");
      out.write("   <div id='create'>\n");
      out.write("    <form id=\"createPopupFormId\" >\n");
      out.write("      <h1>Register Property Management Company</h1>\n");
      out.write("       <div id=\"createErrorId\" class=\"alert alert-block alert-error fade in\" hidden=\"true\" >\n");
      out.write("            <button id=\"alert\" type=\"button\" class=\"close\"  ><span aria-hidden=\"true\">&times;</span><span class=\"sr-only\"></span></button>\n");
      out.write("            <h4 class=\"alert-heading\" animation=\"true\" id=\"createErrorMessageId\">You got an error!</h4>\n");
      out.write("        </div>\n");
      out.write("      <div class=\"form-element1\">\n");
      out.write("        <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("          <tr>\n");
      out.write("            <td width=\"25%\"><label>Company Name:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"companyName\" /></td>\n");
      out.write("            <td width=\"25%\"><label>Authorised Person</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"authorisedPerson\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("           <td><label>Web URL</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"weburl\" /></td>\n");
      out.write("            <td><label>UserName</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" id=\"userName\" name=\"loginObj.username\" onblur=\"userExists()\"/>\n");
      out.write("            <label id=\"userErrorDivId\" class=\"userError\" style=\"color: #FF0000; float: right; display: none;\">Username exists.</label></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Contact Number</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.phoneNumber\" /></td>\n");
      out.write("            <td><label>Email Id:</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"contactDetailsObj.emailId\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>Address Line1</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine1\" /></td>\n");
      out.write("            <td><label>Address Line2</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.addressLine2\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("          <td><label>City</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.city\" /></td>\n");
      out.write("            <td><label>Post Code</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.postCode\" style=\"text-transform: uppercase;\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr>\n");
      out.write("            <td><label>County</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.county\" /></td> \n");
      out.write("            <td><label>Landmark</label>\n");
      out.write("            <input type=\"text\" value=\"\" class=\"\" name=\"addressObj.landmark\" /></td>\n");
      out.write("          </tr>\n");
      out.write("          \n");
      out.write("        </table>\n");
      out.write("      </div>\n");
      out.write("      <div id=\"create_footer\"><input type=\"button\" id=\"createPmcBtnId\" value=\"Create\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("     <div id='delete'>\n");
      out.write("   \t <form id=\"deletePopupFormId\" action=\"javascript:editPopupForm()\">\n");
      out.write("      <h1>Delete Landlord</h1>\n");
      out.write("      \n");
      out.write("      <div id=\"delete_footer\"><input id=\"delete_yes\" type=\"button\" value=\"Yes\" style=\"background-color:#E33A0C\"/>&nbsp&nbsp<input id=\"delete_no\" type=\"button\" value=\"No\" /></div>\n");
      out.write("    </form>\n");
      out.write("  </div> \n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
